import { Character } from './list.component';

const characters: Character[] = [
  { id: 1, name: 'Adalbert Bolger', gender: 'm', race: 'Hobbit' },
  { id: 2, name: 'Adaldrida Bolger', gender: 'f', race: 'Hobbit' },
  { id: 3, name: 'Adalgar Bolger', gender: 'm', race: 'Hobbit' },
  { id: 4, name: 'Adalgrim Took', gender: 'm', race: 'Hobbit' },
  { id: 5, name: 'Adamanta Chubb', gender: 'f', race: 'Hobbit' },
  { id: 6, name: 'Adanel', gender: 'f', race: 'Man' },
  { id: 7, name: 'Adelard Took', gender: 'm', race: 'Hobbit' },
  { id: 8, name: 'Adrahil I', gender: 'm', race: 'Man' },
  { id: 9, name: 'Adrahil II', gender: 'm', race: 'Man' },
  { id: 10, name: 'Ar-Adûnakhôr', gender: 'm', race: 'Man' },
  { id: 11, name: 'Aegnor', gender: 'm', race: 'Elf' },
  { id: 12, name: 'Aerandir', gender: 'm', race: 'Unknown' },
  { id: 13, name: 'Aerin', gender: 'f', race: 'Man' },
  { id: 14, name: 'Aghan', gender: 'm', race: 'Man' },
  { id: 15, name: 'Ailinel', gender: 'f', race: 'Man' },
  { id: 16, name: 'Alatar', gender: 'm', race: 'Maia' },
  { id: 17, name: 'Tar-Alcarin', gender: 'm', race: 'Man' },
  { id: 18, name: 'Tar-Aldarion', gender: 'm', race: 'Man' },
  { id: 19, name: 'Aldor', gender: 'm', race: 'Man' },
  { id: 20, name: 'Alfrida', gender: 'f', race: 'Hobbit' },
  { id: 21, name: 'Algund', gender: 'm', race: 'Man' },
  { id: 22, name: 'Almarian', gender: 'f', race: 'Man' },
  { id: 23, name: 'Almiel', gender: 'f', race: 'Man' },
  { id: 24, name: 'Amandil', gender: 'm', race: 'Man' },
  { id: 25, name: 'Tar-Amandil', gender: 'm', race: 'Man' },
  { id: 26, name: 'Amaranth Brandybuck', gender: 'f', race: 'Hobbit' },
  { id: 27, name: 'Amarië', gender: 'f', race: 'Elf' },
  { id: 28, name: 'Amdír', gender: 'm', race: 'Elf' },
  { id: 29, name: 'Amethyst Hornblower', gender: 'f', race: 'Hobbit' },
  { id: 30, name: 'Amlach', gender: 'm', race: 'Man' },
  { id: 31, name: 'Amlaith', gender: 'm', race: 'Man' },
  { id: 32, name: 'Amras', gender: 'm', race: 'Elf' },
  { id: 33, name: 'Amrod', gender: 'm', race: 'Elf' },
  { id: 34, name: 'Amroth', gender: 'm', race: 'Elf' },
  { id: 35, name: 'Anairë', gender: 'f', race: 'Elf' },
  { id: 36, name: 'Anardil', gender: 'm', race: 'Man' },
  { id: 37, name: 'Anárion', gender: 'm', race: 'Man' },
  { id: 38, name: 'Tar-Anárion', gender: 'm', race: 'Man' },
  { id: 39, name: 'Anborn', gender: 'm', race: 'Man' },
  { id: 40, name: 'Ancalagon', gender: 'm', race: 'Dragon' },
  { id: 41, name: 'Tar-Ancalimë', gender: 'f', race: 'Man' },
  { id: 42, name: 'Tar-Ancalimon', gender: 'm', race: 'Man' },
  { id: 43, name: 'Andreth', gender: 'f', race: 'Man' },
  { id: 44, name: 'Andróg', gender: 'm', race: 'Man' },
  { id: 45, name: 'Andwise Roper', gender: 'm', race: 'Hobbit' },
  { id: 46, name: 'Angbor', gender: 'm', race: 'Man' },
  { id: 47, name: 'Angelica Baggins', gender: 'f', race: 'Hobbit' },
  { id: 48, name: 'Angelimar', gender: 'm', race: 'Man' },
  { id: 49, name: 'Angelimir', gender: 'm', race: 'Man' },
  { id: 50, name: 'Angrim', gender: 'm', race: 'Man' },
  { id: 51, name: 'Angrod', gender: 'm', race: 'Elf' },
  { id: 52, name: 'Annael', gender: 'm', race: 'Elf' },
  { id: 53, name: 'Anson Roper', gender: 'm', race: 'Hobbit' },
  { id: 54, name: 'Arador', gender: 'm', race: 'Man' },
  { id: 55, name: 'Araglas', gender: 'm', race: 'Man' },
  { id: 56, name: 'Aragorn', gender: 'm', race: 'Man' },
  { id: 57, name: 'Aragorn I', gender: 'm', race: 'Man' },
  { id: 58, name: 'Aragost', gender: 'm', race: 'Man' },
  { id: 59, name: 'Arahad I', gender: 'm', race: 'Man' },
  { id: 60, name: 'Arahad II', gender: 'm', race: 'Man' },
  { id: 61, name: 'Arahael', gender: 'm', race: 'Man' },
  { id: 62, name: 'Aranarth', gender: 'm', race: 'Man' },
  { id: 63, name: 'Aranuir', gender: 'm', race: 'Man' },
  { id: 64, name: 'Aranwë', gender: 'm', race: 'Elf' },
  { id: 65, name: 'Araphant', gender: 'm', race: 'Man' },
  { id: 66, name: 'Araphor', gender: 'm', race: 'Man' },
  { id: 67, name: 'Arassuil', gender: 'm', race: 'Man' },
  { id: 68, name: 'Aratan', gender: 'm', race: 'Man' },
  { id: 69, name: 'Arathorn I', gender: 'm', race: 'Man' },
  { id: 70, name: 'Arathorn II', gender: 'm', race: 'Man' },
  { id: 71, name: 'Araval', gender: 'm', race: 'Man' },
  { id: 72, name: 'Aravir', gender: 'm', race: 'Man' },
  { id: 73, name: 'Aravorn', gender: 'm', race: 'Man' },
  { id: 74, name: 'Arciryas', gender: 'm', race: 'Man' },
  { id: 75, name: 'Tar-Ardamin', gender: 'm', race: 'Man' },
  { id: 76, name: 'Ardamir', gender: 'm', race: 'Man' },
  { id: 77, name: 'Aredhel', gender: 'f', race: 'Elf' },
  { id: 78, name: 'Argeleb I', gender: 'm', race: 'Man' },
  { id: 79, name: 'Argeleb II', gender: 'm', race: 'Man' },
  { id: 80, name: 'Argon', gender: 'm', race: 'Elf' },
  { id: 81, name: 'Argonui', gender: 'm', race: 'Man' },
  { id: 82, name: 'Arien', gender: 'f', race: 'Maia' },
  { id: 83, name: 'Arminas', gender: 'm', race: 'Elf' },
  { id: 84, name: 'Arod', gender: 'm', race: 'Horse' },
  { id: 85, name: 'Arroch', gender: '?', race: 'Horse' },
  { id: 86, name: 'Artamir', gender: 'm', race: 'Man' },
  { id: 87, name: 'Arthad', gender: 'm', race: 'Man' },
  { id: 88, name: 'Arvedui', gender: 'm', race: 'Man' },
  { id: 89, name: 'Arvegil', gender: 'm', race: 'Man' },
  { id: 90, name: 'Arveleg I', gender: 'm', race: 'Man' },
  { id: 91, name: 'Arveleg II', gender: 'm', race: 'Man' },
  { id: 92, name: 'Arwen', gender: 'f', race: 'Half-elf' },
  { id: 93, name: 'Asfaloth', gender: '?', race: 'Horse' },
  { id: 94, name: 'Asgon', gender: 'm', race: 'Man' },
  { id: 95, name: 'Asphodel Brandybuck', gender: 'f', race: 'Hobbit' },
  { id: 96, name: 'Atanalcar', gender: 'm', race: 'Man' },
  { id: 97, name: 'Tar-Atanamir', gender: 'm', race: 'Man' },
  { id: 98, name: 'Atanatar I', gender: 'm', race: 'Man' },
  { id: 99, name: 'Atanatar II', gender: 'm', race: 'Man' },
  { id: 100, name: 'Aulë', gender: 'm', race: 'Vala' },
  { id: 101, name: 'Aulendil', gender: 'm', race: 'Man' },
  { id: 102, name: 'Axantur', gender: 'm', race: 'Man' },
  { id: 103, name: 'Azaghâl', gender: 'm', race: 'Dwarf' },
  { id: 104, name: 'Azog', gender: 'm', race: 'Orc' },
  { id: 105, name: 'Bain', gender: 'm', race: 'Man' },
  { id: 106, name: 'Balbo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 107, name: 'Baldor', gender: 'm', race: 'Man' },
  { id: 108, name: 'Balin', gender: 'm', race: 'Dwarf' },
  { id: 109, name: 'Bandobras Took', gender: 'm', race: 'Hobbit' },
  { id: 110, name: 'Barach', gender: 'm', race: 'Man' },
  { id: 111, name: 'Baragund', gender: 'm', race: 'Man' },
  { id: 112, name: 'Barahir', gender: 'm', race: 'Man' },
  { id: 113, name: 'Barahir', gender: 'm', race: 'Man' },
  { id: 114, name: 'Barahir', gender: 'm', race: 'Man' },
  { id: 115, name: 'Baran', gender: 'm', race: 'Man' },
  { id: 116, name: 'Baranor', gender: 'm', race: 'Man' },
  { id: 117, name: 'Bard II', gender: 'm', race: 'Man' },
  { id: 118, name: 'Bard the Bowman', gender: 'm', race: 'Man' },
  { id: 119, name: 'Barliman Butterbur', gender: 'm', race: 'Man' },
  { id: 120, name: 'Basso Boffin', gender: 'm', race: 'Hobbit' },
  { id: 121, name: 'Beechbone', gender: 'm', race: 'Ent' },
  { id: 122, name: 'Belba Baggins', gender: 'f', race: 'Hobbit' },
  { id: 123, name: 'Beldir', gender: 'm', race: 'Man' },
  { id: 124, name: 'Beldis', gender: 'f', race: 'Man' },
  { id: 125, name: 'Belecthor I', gender: 'm', race: 'Man' },
  { id: 126, name: 'Belecthor II', gender: 'm', race: 'Man' },
  { id: 127, name: 'Beleg', gender: 'm', race: 'Man' },
  { id: 128, name: 'Beleg Cúthalion', gender: 'm', race: 'Elf' },
  { id: 129, name: 'Belegorn', gender: 'm', race: 'Man' },
  { id: 130, name: 'Belegund', gender: 'm', race: 'Man' },
  { id: 131, name: 'Belemir', gender: 'm', race: 'Man' },
  { id: 132, name: 'Belen', gender: 'm', race: 'Man' },
  { id: 133, name: 'Bell Goodchild', gender: 'f', race: 'Hobbit' },
  { id: 134, name: 'Belladonna Took', gender: 'f', race: 'Hobbit' },
  { id: 135, name: 'Bëor', gender: 'm', race: 'Man' },
  { id: 136, name: 'Beorn', gender: 'm', race: 'Man' },
  { id: 137, name: 'Bereg', gender: 'm', race: 'Man' },
  { id: 138, name: 'Beregar', gender: 'm', race: 'Man' },
  { id: 139, name: 'Beregond', gender: 'm', race: 'Man' },
  { id: 140, name: 'Beregond', gender: 'm', race: 'Man' },
  { id: 141, name: 'Beren', gender: 'm', race: 'Man' },
  { id: 142, name: 'Beren Erchamion', gender: 'm', race: 'Man' },
  { id: 143, name: 'Bereth', gender: 'f', race: 'Man' },
  { id: 144, name: 'Bergil', gender: 'm', race: 'Man' },
  { id: 145, name: 'Beril', gender: 'f', race: 'Man' },
  { id: 146, name: 'Berilac Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 147, name: 'Bert', gender: 'm', race: 'Troll' },
  { id: 148, name: 'Berúthiel', gender: 'f', race: 'Man' },
  { id: 149, name: 'Berylla Boffin', gender: 'f', race: 'Hobbit' },
  { id: 150, name: 'Bifur', gender: 'm', race: 'Dwarf' },
  { id: 151, name: 'Bilbo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 152, name: 'Bilbo Gardner', gender: 'm', race: 'Hobbit' },
  { id: 153, name: 'Bill', gender: 'm', race: 'Troll' },
  { id: 154, name: 'Bill', gender: 'm', race: 'Pony' },
  { id: 155, name: 'Bill Ferny', gender: 'm', race: 'Man' },
  { id: 156, name: 'Bingo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 157, name: 'Blanco', gender: 'm', race: 'Hobbit' },
  { id: 158, name: 'Blanco Bracegirdle', gender: 'm', race: 'Hobbit' },
  { id: 159, name: 'Bob', gender: 'm', race: 'Hobbit' },
  { id: 160, name: 'Bodo Proudfoot', gender: 'm', race: 'Hobbit' },
  { id: 161, name: 'Bofur', gender: 'm', race: 'Dwarf' },
  { id: 162, name: 'Bolg', gender: 'm', race: 'Orc' },
  { id: 163, name: 'Bombur', gender: 'm', race: 'Dwarf' },
  { id: 164, name: 'Bór', gender: 'm', race: 'Man' },
  { id: 165, name: 'Borin', gender: 'm', race: 'Dwarf' },
  { id: 166, name: 'Borlach', gender: 'm', race: 'Man' },
  { id: 167, name: 'Borlad', gender: 'm', race: 'Man' },
  { id: 168, name: 'Boromir', gender: 'm', race: 'Man' },
  { id: 169, name: 'Boromir', gender: 'm', race: 'Man' },
  { id: 170, name: 'Boromir', gender: 'm', race: 'Man' },
  { id: 171, name: 'Boron', gender: 'm', race: 'Man' },
  { id: 172, name: 'Borondir', gender: 'm', race: 'Man' },
  { id: 173, name: 'Borthand', gender: 'm', race: 'Man' },
  { id: 174, name: 'Bosco Boffin', gender: 'm', race: 'Hobbit' },
  { id: 175, name: 'Bowman Cotton', gender: 'm', race: 'Hobbit' },
  { id: 176, name: 'Brand', gender: 'm', race: 'Man' },
  { id: 177, name: 'Brandir', gender: 'm', race: 'Man' },
  { id: 178, name: 'Bregalad', gender: 'm', race: 'Ent' },
  { id: 179, name: 'Brego', gender: 'm', race: 'Man' },
  { id: 180, name: 'Bregolas', gender: 'm', race: 'Man' },
  { id: 181, name: 'Briffo Boffin', gender: 'm', race: 'Hobbit' },
  { id: 182, name: 'Brodda', gender: 'm', race: 'Man' },
  { id: 183, name: 'Bruno Bracegirdle', gender: 'm', race: 'Hobbit' },
  { id: 184, name: 'Brytta', gender: 'm', race: 'Man' },
  { id: 185, name: 'Bucca', gender: 'm', race: 'Hobbit' },
  { id: 186, name: 'Buffo Boffin', gender: 'm', race: 'Hobbit' },
  { id: 187, name: 'Bungo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 188, name: 'Calimehtar', gender: 'm', race: 'Man' },
  { id: 189, name: 'Caliondo', gender: 'm', race: 'Man' },
  { id: 190, name: 'Calmacil', gender: 'm', race: 'Man' },
  { id: 191, name: 'Tar-Calmacil', gender: 'm', race: 'Man' },
  { id: 192, name: 'Camellia Sackville', gender: 'f', race: 'Hobbit' },
  { id: 193, name: 'Caranthir', gender: 'm', race: 'Elf' },
  { id: 194, name: 'Carc', gender: 'm', race: 'Raven' },
  { id: 195, name: 'Carcharoth', gender: 'm', race: 'Werewolf' },
  { id: 196, name: 'Carl Cotton', gender: 'm', race: 'Hobbit' },
  { id: 197, name: 'Castamir the Usurper', gender: 'm', race: 'Man' },
  { id: 198, name: 'Celandine Brandybuck', gender: 'f', race: 'Hobbit' },
  { id: 199, name: 'Celeborn', gender: 'm', race: 'Elf' },
  { id: 200, name: 'Celebrían', gender: 'f', race: 'Elf' },
  { id: 201, name: 'Celebrimbor', gender: 'm', race: 'Elf' },
  { id: 202, name: 'Celebrindor', gender: 'm', race: 'Man' },
  { id: 203, name: 'Celegorm', gender: 'm', race: 'Elf' },
  { id: 204, name: 'Celepharn', gender: 'm', race: 'Man' },
  { id: 205, name: 'Cemendur', gender: 'm', race: 'Man' },
  { id: 206, name: 'Ceorl', gender: 'm', race: 'Man' },
  { id: 207, name: 'Chica Chubb', gender: 'f', race: 'Hobbit' },
  { id: 208, name: 'Círdan', gender: 'm', race: 'Elf' },
  { id: 209, name: 'Cirion', gender: 'm', race: 'Man' },
  { id: 210, name: 'Ciryandil', gender: 'm', race: 'Man' },
  { id: 211, name: 'Tar-Ciryatan', gender: 'm', race: 'Man' },
  { id: 212, name: 'Ciryatur', gender: 'm', race: 'Man' },
  { id: 213, name: 'Ciryon', gender: 'm', race: 'Man' },
  { id: 214, name: 'Cora Goodbody', gender: 'f', race: 'Hobbit' },
  { id: 215, name: 'Cotman', gender: 'm', race: 'Hobbit' },
  { id: 216, name: 'Cottar', gender: 'm', race: 'Hobbit' },
  { id: 217, name: 'Curufin', gender: 'm', race: 'Elf' },
  { id: 218, name: 'Daeron', gender: 'm', race: 'Elf' },
  { id: 219, name: 'Dagnir', gender: 'm', race: 'Man' },
  { id: 220, name: 'Dáin I', gender: 'm', race: 'Dwarf' },
  { id: 221, name: 'Dáin II', gender: 'm', race: 'Dwarf' },
  { id: 222, name: 'Dairuin', gender: 'm', race: 'Man' },
  { id: 223, name: 'Daisy Baggins', gender: 'f', race: 'Hobbit' },
  { id: 224, name: 'Daisy Gardner', gender: 'f', race: 'Hobbit' },
  { id: 225, name: 'Damrod', gender: 'm', race: 'Man' },
  { id: 226, name: 'Déagol', gender: 'm', race: 'Hobbit' },
  { id: 227, name: 'Denethor', gender: 'm', race: 'Elf' },
  { id: 228, name: 'Denethor I', gender: 'm', race: 'Man' },
  { id: 229, name: 'Denethor II', gender: 'm', race: 'Man' },
  { id: 230, name: 'Déor', gender: 'm', race: 'Man' },
  { id: 231, name: 'Déorwine', gender: 'm', race: 'Man' },
  { id: 232, name: 'Derufin', gender: 'm', race: 'Man' },
  { id: 233, name: 'Dervorin', gender: 'm', race: 'Man' },
  { id: 234, name: 'Diamond', gender: 'f', race: 'Hobbit' },
  { id: 235, name: 'Dina Diggle', gender: 'f', race: 'Hobbit' },
  { id: 236, name: 'Dinodas Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 237, name: 'Dior', gender: 'm', race: 'Half-elf' },
  { id: 238, name: 'Dior', gender: 'm', race: 'Man' },
  { id: 239, name: 'Dírhael', gender: 'm', race: 'Man' },
  { id: 240, name: 'Dírhavel', gender: 'm', race: 'Man' },
  { id: 241, name: 'Dís', gender: 'f', race: 'Dwarf' },
  { id: 242, name: 'Doderic Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 243, name: 'Dodinas Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 244, name: 'Donnamira Took', gender: 'f', race: 'Hobbit' },
  { id: 245, name: 'Dora Baggins', gender: 'f', race: 'Hobbit' },
  { id: 246, name: 'Dori', gender: 'm', race: 'Dwarf' },
  { id: 247, name: 'Dorlas', gender: 'm', race: 'Man' },
  { id: 248, name: 'Draugluin', gender: 'm', race: 'Werewolf' },
  { id: 249, name: 'Drogo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 250, name: 'Druda Burrows', gender: 'f', race: 'Hobbit' },
  { id: 251, name: 'Dudo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 252, name: 'Duilin', gender: 'm', race: 'Man' },
  { id: 253, name: 'Duinhir', gender: 'm', race: 'Man' },
  { id: 254, name: 'Dúnhere', gender: 'm', race: 'Man' },
  { id: 255, name: 'Durin I', gender: 'm', race: 'Dwarf' },
  { id: 256, name: 'Durin II', gender: 'm', race: 'Dwarf' },
  { id: 257, name: 'Durin III', gender: 'm', race: 'Dwarf' },
  { id: 258, name: 'Durin IV', gender: 'm', race: 'Dwarf' },
  { id: 259, name: 'Durin V', gender: 'm', race: 'Dwarf' },
  { id: 260, name: 'Durin VI', gender: 'm', race: 'Dwarf' },
  { id: 261, name: 'Durin VII', gender: 'm', race: 'Dwarf' },
  { id: 262, name: 'Dwalin', gender: 'm', race: 'Dwarf' },
  { id: 263, name: 'Eärendil', gender: 'm', race: 'Half-elf' },
  { id: 264, name: 'Eärendil', gender: 'm', race: 'Man' },
  { id: 265, name: 'Eärendur', gender: 'm', race: 'Man' },
  { id: 266, name: 'Eärendur', gender: 'm', race: 'Man' },
  { id: 267, name: 'Eärendur', gender: 'm', race: 'Man' },
  { id: 268, name: 'Eärnil I', gender: 'm', race: 'Man' },
  { id: 269, name: 'Eärnil II', gender: 'm', race: 'Man' },
  { id: 270, name: 'Eärnur', gender: 'm', race: 'Man' },
  { id: 271, name: 'Eärwen', gender: 'f', race: 'Elf' },
  { id: 272, name: 'Ecthelion I', gender: 'm', race: 'Man' },
  { id: 273, name: 'Ecthelion II', gender: 'm', race: 'Man' },
  { id: 274, name: 'Ecthelion of the Fountain', gender: 'm', race: 'Elf' },
  { id: 275, name: 'Edrahil', gender: 'm', race: 'Elf' },
  { id: 276, name: 'Egalmoth', gender: 'm', race: 'Man' },
  { id: 277, name: 'Egalmoth', gender: 'm', race: 'Elf' },
  { id: 278, name: 'Eglantine Banks', gender: 'f', race: 'Hobbit' },
  { id: 279, name: 'Eilinel', gender: 'f', race: 'Man' },
  { id: 280, name: 'Elanor Gardner', gender: 'f', race: 'Hobbit' },
  { id: 281, name: 'Elatan', gender: 'm', race: 'Man' },
  { id: 282, name: 'Elboron', gender: 'm', race: 'Man' },
  { id: 283, name: 'Eldacar', gender: 'm', race: 'Man' },
  { id: 284, name: 'Eldacar', gender: 'm', race: 'Man' },
  { id: 285, name: 'Eldalótë', gender: 'f', race: 'Elf' },
  { id: 286, name: 'Eldarion', gender: 'm', race: 'Man' },
  { id: 287, name: 'Elemmakil', gender: 'm', race: 'Elf' },
  { id: 288, name: 'Elemmírë', gender: '?', race: 'Elf' },
  { id: 289, name: 'Elendil', gender: 'm', race: 'Man' },
  { id: 290, name: 'Tar-Elendil', gender: 'm', race: 'Man' },
  { id: 291, name: 'Elendur', gender: 'm', race: 'Man' },
  { id: 292, name: 'Elenwë', gender: 'f', race: 'Elf' },
  { id: 293, name: 'Elfhelm', gender: 'm', race: 'Man' },
  { id: 294, name: 'Elfhild', gender: 'f', race: 'Man' },
  { id: 295, name: 'Elfstan Fairbairn', gender: 'm', race: 'Hobbit' },
  { id: 296, name: 'Elfwine', gender: 'm', race: 'Man' },
  { id: 297, name: 'Elladan', gender: 'm', race: 'Half-elf' },
  { id: 298, name: 'Elmo', gender: 'm', race: 'Elf' },
  { id: 299, name: 'Elrohir', gender: 'm', race: 'Half-elf' },
  { id: 300, name: 'Elrond', gender: 'm', race: 'Half-elf' },
  { id: 301, name: 'Elros', gender: 'm', race: 'Half-elf' },
  { id: 302, name: 'Eluréd', gender: 'm', race: 'Half-elf' },
  { id: 303, name: 'Elurín', gender: 'm', race: 'Half-elf' },
  { id: 304, name: 'Elwing', gender: 'f', race: 'Half-elf' },
  { id: 305, name: 'Emeldir', gender: 'f', race: 'Man' },
  { id: 306, name: 'Enel', gender: 'm', race: 'Elf' },
  { id: 307, name: 'Enerdhil', gender: 'm', race: 'Elf' },
  { id: 308, name: 'Eofor', gender: 'm', race: 'Man' },
  { id: 309, name: 'Eöl', gender: 'm', race: 'Elf' },
  { id: 310, name: 'Éomer', gender: 'm', race: 'Man' },
  { id: 311, name: 'Éomund', gender: 'm', race: 'Man' },
  { id: 312, name: 'Eönwë', gender: 'm', race: 'Maia' },
  { id: 313, name: 'Eorl the Young', gender: 'm', race: 'Man' },
  { id: 314, name: 'Éothain', gender: 'm', race: 'Man' },
  { id: 315, name: 'Éowyn', gender: 'f', race: 'Man' },
  { id: 316, name: 'Eradan', gender: 'm', race: 'Man' },
  { id: 317, name: 'Erchirion', gender: 'm', race: 'Man' },
  { id: 318, name: 'Erellont', gender: 'm', race: 'Unknown' },
  { id: 319, name: 'Erendis', gender: 'f', race: 'Man' },
  { id: 320, name: 'Erestor', gender: 'm', race: 'Elf' },
  { id: 321, name: 'Erkenbrand', gender: 'm', race: 'Man' },
  { id: 322, name: 'Erling Greenhand', gender: 'm', race: 'Hobbit' },
  { id: 323, name: 'Esmeralda Brandybuck', gender: 'f', race: 'Hobbit' },
  { id: 324, name: 'Estë', gender: 'f', race: 'Vala' },
  { id: 325, name: 'Estella Bolger', gender: 'f', race: 'Hobbit' },
  { id: 326, name: 'Estelmo', gender: 'm', race: 'Man' },
  { id: 327, name: 'Everard Took', gender: 'm', race: 'Hobbit' },
  { id: 328, name: 'Falco Chubb-Baggins', gender: 'm', race: 'Hobbit' },
  { id: 329, name: 'Faramir', gender: 'm', race: 'Man' },
  { id: 330, name: 'Faramir Took', gender: 'm', race: 'Hobbit' },
  { id: 331, name: 'Farin', gender: 'm', race: 'Dwarf' },
  { id: 332, name: 'Fastolph Bolger', gender: 'm', race: 'Hobbit' },
  { id: 333, name: 'Fastred', gender: 'm', race: 'Hobbit' },
  { id: 334, name: 'Fastred', gender: 'm', race: 'Man' },
  { id: 335, name: 'Fastred', gender: 'm', race: 'Man' },
  { id: 336, name: 'Fatty Lumpkin', gender: 'm', race: 'Pony' },
  { id: 337, name: 'Fëanor', gender: 'm', race: 'Elf' },
  { id: 338, name: 'Felaróf', gender: 'm', race: 'Horse' },
  { id: 339, name: 'Fengel', gender: 'm', race: 'Man' },
  { id: 340, name: 'Ferdinand Took', gender: 'm', race: 'Hobbit' },
  { id: 341, name: 'Ferumbras Took I', gender: 'm', race: 'Hobbit' },
  { id: 342, name: 'Ferumbras Took II', gender: 'm', race: 'Hobbit' },
  { id: 343, name: 'Ferumbras Took III', gender: 'm', race: 'Hobbit' },
  { id: 344, name: 'Fíli', gender: 'm', race: 'Dwarf' },
  { id: 345, name: 'Filibert Bolger', gender: 'm', race: 'Hobbit' },
  { id: 346, name: 'Fimbrethil', gender: 'f', race: 'Ent' },
  { id: 347, name: 'Finarfin', gender: 'm', race: 'Elf' },
  { id: 348, name: 'Findegil', gender: 'm', race: 'Man' },
  { id: 349, name: 'Findis', gender: 'f', race: 'Elf' },
  { id: 350, name: 'Finduilas', gender: 'f', race: 'Elf' },
  { id: 351, name: 'Finduilas', gender: 'f', race: 'Man' },
  { id: 352, name: 'Finglas', gender: 'm', race: 'Ent' },
  { id: 353, name: 'Fingolfin', gender: 'm', race: 'Elf' },
  { id: 354, name: 'Fingon', gender: 'm', race: 'Elf' },
  { id: 355, name: 'Finrod', gender: 'm', race: 'Elf' },
  { id: 356, name: 'Finwë', gender: 'm', race: 'Elf' },
  { id: 357, name: 'Firefoot', gender: 'm', race: 'Horse' },
  { id: 358, name: 'Fíriel Fairbairn', gender: 'f', race: 'Hobbit' },
  { id: 359, name: 'Fladrif', gender: 'm', race: 'Ent' },
  { id: 360, name: 'Flambard Took', gender: 'm', race: 'Hobbit' },
  { id: 361, name: 'Flói', gender: 'm', race: 'Dwarf' },
  { id: 362, name: 'Folca', gender: 'm', race: 'Man' },
  { id: 363, name: 'Folco Boffin', gender: 'm', race: 'Hobbit' },
  { id: 364, name: 'Folcred', gender: 'm', race: 'Man' },
  { id: 365, name: 'Folcwine', gender: 'm', race: 'Man' },
  { id: 366, name: 'Forlong', gender: 'm', race: 'Man' },
  { id: 367, name: 'Forthwini', gender: 'm', race: 'Man' },
  { id: 368, name: 'Fortinbras Took I', gender: 'm', race: 'Hobbit' },
  { id: 369, name: 'Fortinbras Took II', gender: 'm', race: 'Hobbit' },
  { id: 370, name: 'Forweg', gender: 'm', race: 'Man' },
  { id: 371, name: 'Fosco Baggins', gender: 'm', race: 'Hobbit' },
  { id: 372, name: 'Fram', gender: 'm', race: 'Man' },
  { id: 373, name: 'Frár', gender: 'm', race: 'Dwarf' },
  { id: 374, name: 'Fréa', gender: 'm', race: 'Man' },
  { id: 375, name: 'Fréaláf Hildeson', gender: 'm', race: 'Man' },
  { id: 376, name: 'Fréawine', gender: 'm', race: 'Man' },
  { id: 377, name: 'Freca', gender: 'm', race: 'Man' },
  { id: 378, name: 'Fredegar Bolger', gender: 'm', race: 'Hobbit' },
  { id: 379, name: 'Frerin', gender: 'm', race: 'Dwarf' },
  { id: 380, name: 'Frodo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 381, name: 'Frodo Gardner', gender: 'm', race: 'Hobbit' },
  { id: 382, name: 'Frór', gender: 'm', race: 'Dwarf' },
  { id: 383, name: 'Frumgar', gender: 'm', race: 'Man' },
  { id: 384, name: 'Fuinur', gender: 'm', race: 'Man' },
  { id: 385, name: 'Fundin', gender: 'm', race: 'Dwarf' },
  { id: 386, name: 'Galadhon', gender: 'm', race: 'Elf' },
  { id: 387, name: 'Galador', gender: 'm', race: 'Half-elf' },
  { id: 388, name: 'Galadriel', gender: 'f', race: 'Elf' },
  { id: 389, name: 'Galathil', gender: 'm', race: 'Elf' },
  { id: 390, name: 'Galdor', gender: 'm', race: 'Elf' },
  { id: 391, name: 'Galdor the Tall', gender: 'm', race: 'Man' },
  { id: 392, name: 'Galion', gender: 'm', race: 'Elf' },
  { id: 393, name: 'Gálmód', gender: 'm', race: 'Man' },
  { id: 394, name: 'Gamil Zirak', gender: 'm', race: 'Dwarf' },
  { id: 395, name: 'Gamling', gender: 'm', race: 'Man' },
  { id: 396, name: 'Gandalf', gender: 'm', race: 'Maia' },
  { id: 397, name: 'Gárulf', gender: 'm', race: 'Man' },
  { id: 398, name: 'Gelmir', gender: 'm', race: 'Elf' },
  { id: 399, name: 'Gelmir', gender: 'm', race: 'Elf' },
  { id: 400, name: 'Gerda Boffin', gender: 'f', race: 'Hobbit' },
  { id: 401, name: 'Gerontius Took', gender: 'm', race: 'Hobbit' },
  { id: 402, name: 'Gethron', gender: 'm', race: 'Man' },
  { id: 403, name: 'Ghân-buri-Ghân', gender: 'm', race: 'Man' },
  { id: 404, name: 'Gildis', gender: 'f', race: 'Man' },
  { id: 405, name: 'Gildor', gender: 'm', race: 'Man' },
  { id: 406, name: 'Gildor Inglorion', gender: 'm', race: 'Elf' },
  { id: 407, name: 'Gil-galad', gender: 'm', race: 'Elf' },
  { id: 408, name: 'Gilly Brownlock', gender: 'f', race: 'Hobbit' },
  { id: 409, name: 'Gilmith', gender: 'f', race: 'Half-elf' },
  { id: 410, name: 'Gilraen', gender: 'f', race: 'Man' },
  { id: 411, name: 'Gimilkhâd', gender: 'm', race: 'Man' },
  { id: 412, name: 'Gimilzagar', gender: 'm', race: 'Man' },
  { id: 413, name: 'Ar-Gimilzôr', gender: 'm', race: 'Man' },
  { id: 414, name: 'Gimli', gender: 'm', race: 'Dwarf' },
  { id: 415, name: 'Girion', gender: 'm', race: 'Man' },
  { id: 416, name: 'Glaurung', gender: 'm', race: 'Dragon' },
  { id: 417, name: 'Gléowine', gender: 'm', race: 'Man' },
  { id: 418, name: 'Glirhuin', gender: 'm', race: 'Man' },
  { id: 419, name: 'Glóin', gender: 'm', race: 'Dwarf' },
  { id: 420, name: 'Glóin', gender: 'm', race: 'Dwarf' },
  { id: 421, name: 'Glóredhel', gender: 'f', race: 'Man' },
  { id: 422, name: 'Glorfindel', gender: 'm', race: 'Elf' },
  { id: 423, name: 'Glorfindel', gender: 'm', race: 'Elf' },
  { id: 424, name: 'Golasgil', gender: 'm', race: 'Man' },
  { id: 425, name: 'Goldberry', gender: 'f', race: 'Unknown' },
  { id: 426, name: 'Goldilocks Gardner', gender: 'f', race: 'Hobbit' },
  { id: 427, name: 'Goldwine', gender: 'm', race: 'Man' },
  { id: 428, name: 'Golfimbul', gender: 'm', race: 'Orc' },
  { id: 429, name: 'Gollum', gender: 'm', race: 'Hobbit' },
  { id: 430, name: 'Gorbadoc Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 431, name: 'Gorbag', gender: 'm', race: 'Orc' },
  { id: 432, name: 'Gorbulas Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 433, name: 'Gorhendad Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 434, name: 'Gorlim', gender: 'm', race: 'Man' },
  { id: 435, name: 'Gormadoc Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 436, name: 'Gothmog', gender: 'm', race: 'Maia' },
  { id: 437, name: 'Gothmog', gender: 'm', race: 'Unknown' },
  { id: 438, name: 'Gram', gender: 'm', race: 'Man' },
  { id: 439, name: 'Griffo Boffin', gender: 'm', race: 'Hobbit' },
  { id: 440, name: 'Gríma Wormtongue', gender: 'm', race: 'Man' },
  { id: 441, name: 'Grimbeorn', gender: 'm', race: 'Man' },
  { id: 442, name: 'Grimbold', gender: 'm', race: 'Man' },
  { id: 443, name: 'Grishnákh', gender: 'm', race: 'Orc' },
  { id: 444, name: 'Grithnir', gender: 'm', race: 'Man' },
  { id: 445, name: 'Gróin', gender: 'm', race: 'Dwarf' },
  { id: 446, name: 'Grór', gender: 'm', race: 'Dwarf' },
  { id: 447, name: 'Gruffo Boffin', gender: 'm', race: 'Hobbit' },
  { id: 448, name: 'Guilin', gender: 'm', race: 'Elf' },
  { id: 449, name: 'Gundabald Bolger', gender: 'm', race: 'Hobbit' },
  { id: 450, name: 'Gundahad Bolger', gender: 'm', race: 'Hobbit' },
  { id: 451, name: 'Gundahar Bolger', gender: 'm', race: 'Hobbit' },
  { id: 452, name: 'Gundolpho Bolger', gender: 'm', race: 'Hobbit' },
  { id: 453, name: 'Gundor', gender: 'm', race: 'Man' },
  { id: 454, name: 'Guthláf', gender: 'm', race: 'Man' },
  { id: 455, name: 'Gwaihir', gender: 'm', race: 'Eagle' },
  { id: 456, name: 'Gwindor', gender: 'm', race: 'Elf' },
  { id: 457, name: 'Hador', gender: 'm', race: 'Man' },
  { id: 458, name: 'Hador Lórindol', gender: 'm', race: 'Man' },
  { id: 459, name: 'Halbarad', gender: 'm', race: 'Man' },
  { id: 460, name: 'Haldad', gender: 'm', race: 'Man' },
  { id: 461, name: 'Haldan', gender: 'm', race: 'Man' },
  { id: 462, name: 'Haldar', gender: 'm', race: 'Man' },
  { id: 463, name: 'Haldir', gender: 'm', race: 'Elf' },
  { id: 464, name: 'Haldir', gender: 'm', race: 'Man' },
  { id: 465, name: 'Haleth', gender: 'f', race: 'Man' },
  { id: 466, name: 'Halfast Gamgee', gender: 'm', race: 'Hobbit' },
  { id: 467, name: 'Halfred Gamgee', gender: 'm', race: 'Hobbit' },
  { id: 468, name: 'Halfred Greenhand', gender: 'm', race: 'Hobbit' },
  { id: 469, name: 'Hallacar', gender: 'm', race: 'Man' },
  { id: 470, name: 'Hallas', gender: 'm', race: 'Man' },
  { id: 471, name: 'Hallatan', gender: 'm', race: 'Man' },
  { id: 472, name: 'Halmir', gender: 'm', race: 'Man' },
  { id: 473, name: 'Háma', gender: 'm', race: 'Man' },
  { id: 474, name: 'Hamfast of Gamwich', gender: 'm', race: 'Hobbit' },
  { id: 475, name: 'Hamfast Gamgee', gender: 'm', race: 'Hobbit' },
  { id: 476, name: 'Hamfast Gardner', gender: 'm', race: 'Hobbit' },
  { id: 477, name: 'Hamson Gamgee', gender: 'm', race: 'Hobbit' },
  { id: 478, name: 'Hanna Goldworthy', gender: 'f', race: 'Hobbit' },
  { id: 479, name: 'Harding', gender: 'm', race: 'Man' },
  { id: 480, name: 'Harding of the Hill', gender: 'm', race: 'Hobbit' },
  { id: 481, name: 'Hareth', gender: 'm', race: 'Man' },
  { id: 482, name: 'Harry Goatleaf', gender: 'm', race: 'Man' },
  { id: 483, name: 'Hasufel', gender: 'm', race: 'Horse' },
  { id: 484, name: 'Hatholdir', gender: 'm', race: 'Man' },
  { id: 485, name: 'Helm Hammerhand', gender: 'm', race: 'Man' },
  { id: 486, name: 'Hending', gender: 'm', race: 'Hobbit' },
  { id: 487, name: 'Herefara', gender: 'm', race: 'Man' },
  { id: 488, name: 'Heribald Bolger', gender: 'm', race: 'Hobbit' },
  { id: 489, name: 'Herion', gender: 'm', race: 'Man' },
  { id: 490, name: 'Herubrand', gender: 'm', race: 'Man' },
  { id: 491, name: 'Herucalmo', gender: 'm', race: 'Man' },
  { id: 492, name: 'Herugar Bolger', gender: 'm', race: 'Hobbit' },
  { id: 493, name: 'Herumor', gender: 'm', race: 'Man' },
  { id: 494, name: 'Hilda Bracegirdle', gender: 'f', race: 'Hobbit' },
  { id: 495, name: 'Hildibrand Took', gender: 'm', race: 'Hobbit' },
  { id: 496, name: 'Hildifons Took', gender: 'm', race: 'Hobbit' },
  { id: 497, name: 'Hildigard Took', gender: 'f', race: 'Hobbit' },
  { id: 498, name: 'Hildigrim Took', gender: 'm', race: 'Hobbit' },
  { id: 499, name: 'Hirgon', gender: 'm', race: 'Man' },
  { id: 500, name: 'Hiril', gender: 'f', race: 'Man' },
  { id: 501, name: 'Hirluin', gender: 'm', race: 'Man' },
  { id: 502, name: 'Hob Gammidge', gender: 'm', race: 'Hobbit' },
  { id: 503, name: 'Hob Hayward', gender: 'm', race: 'Hobbit' },
  { id: 504, name: 'Hobson Gamgee', gender: 'm', race: 'Hobbit' },
  { id: 505, name: 'Holfast Gardner', gender: 'm', race: 'Hobbit' },
  { id: 506, name: 'Holman Cotton', gender: 'm', race: 'Hobbit' },
  { id: 507, name: 'Holman Greenhand', gender: 'm', race: 'Hobbit' },
  { id: 508, name: 'Horn', gender: 'm', race: 'Man' },
  { id: 509, name: 'Huan', gender: 'm', race: 'Wolf' },
  { id: 510, name: 'Hugo Boffin', gender: 'm', race: 'Hobbit' },
  { id: 511, name: 'Hugo Bracegirdle', gender: 'm', race: 'Hobbit' },
  { id: 512, name: 'Hundar', gender: 'f', race: 'Man' },
  { id: 513, name: 'Hunthor', gender: 'm', race: 'Man' },
  { id: 514, name: 'Huor', gender: 'm', race: 'Man' },
  { id: 515, name: 'Húrin', gender: 'm', race: 'Man' },
  { id: 516, name: 'Húrin I', gender: 'm', race: 'Man' },
  { id: 517, name: 'Húrin II', gender: 'm', race: 'Man' },
  { id: 518, name: 'Hyarmendacil I', gender: 'm', race: 'Man' },
  { id: 519, name: 'Hyarmendacil II', gender: 'm', race: 'Man' },
  { id: 520, name: 'Îbal', gender: 'm', race: 'Man' },
  { id: 521, name: 'Ibûn', gender: 'm', race: 'Dwarf' },
  { id: 522, name: 'Idril', gender: 'f', race: 'Elf' },
  { id: 523, name: 'Ilberic Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 524, name: 'Ilmarë', gender: 'f', race: 'Maia' },
  { id: 525, name: 'Imin', gender: 'm', race: 'Elf' },
  { id: 526, name: 'Imrahil', gender: 'm', race: 'Man' },
  { id: 527, name: 'Indis', gender: 'f', race: 'Elf' },
  { id: 528, name: 'Ingwë', gender: 'm', race: 'Elf' },
  { id: 529, name: 'Ingwion', gender: 'm', race: 'Elf' },
  { id: 530, name: 'Inzilbêth', gender: 'f', race: 'Man' },
  { id: 531, name: 'Ioreth', gender: 'f', race: 'Man' },
  { id: 532, name: 'Iorlas', gender: 'm', race: 'Man' },
  { id: 533, name: 'Írildë', gender: 'f', race: 'Man' },
  { id: 534, name: 'Irimë', gender: 'f', race: 'Elf' },
  { id: 535, name: 'Isembard Took', gender: 'm', race: 'Hobbit' },
  { id: 536, name: 'Isembold Took', gender: 'm', race: 'Hobbit' },
  { id: 537, name: 'Isengar Took', gender: 'm', race: 'Hobbit' },
  { id: 538, name: 'Isengrim Took I', gender: 'm', race: 'Hobbit' },
  { id: 539, name: 'Isengrim Took II', gender: 'm', race: 'Hobbit' },
  { id: 540, name: 'Isengrim Took III', gender: 'm', race: 'Hobbit' },
  { id: 541, name: 'Isildur', gender: 'm', race: 'Man' },
  { id: 542, name: 'Isilmë', gender: 'f', race: 'Man' },
  { id: 543, name: 'Isilmo', gender: 'm', race: 'Man' },
  { id: 544, name: 'Isumbras Took I', gender: 'm', race: 'Hobbit' },
  { id: 545, name: 'Isumbras Took II', gender: 'm', race: 'Hobbit' },
  { id: 546, name: 'Isumbras Took III', gender: 'm', race: 'Hobbit' },
  { id: 547, name: 'Isumbras Took IV', gender: 'm', race: 'Hobbit' },
  { id: 548, name: 'Ivorwen', gender: 'f', race: 'Man' },
  { id: 549, name: 'Ivy Goodenough', gender: 'f', race: 'Hobbit' },
  { id: 550, name: 'Jago Boffin', gender: 'm', race: 'Hobbit' },
  { id: 551, name: 'Jessamine Boffin', gender: 'f', race: 'Hobbit' },
  { id: 552, name: 'Khamûl', gender: 'm', race: 'Man' },
  { id: 553, name: 'Khîm', gender: 'm', race: 'Dwarf' },
  { id: 554, name: 'Kíli', gender: 'm', race: 'Dwarf' },
  { id: 555, name: 'Lagduf', gender: 'm', race: 'Orc' },
  { id: 556, name: 'Lalia Clayhanger', gender: 'f', race: 'Hobbit' },
  { id: 557, name: 'Landroval', gender: 'm', race: 'Eagle' },
  { id: 558, name: 'Largo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 559, name: 'Laura Grubb', gender: 'f', race: 'Hobbit' },
  { id: 560, name: 'Lavender Grubb', gender: 'f', race: 'Hobbit' },
  { id: 561, name: 'Legolas', gender: 'm', race: 'Elf' },
  { id: 562, name: 'Lenwë', gender: 'm', race: 'Elf' },
  { id: 563, name: 'Léod', gender: 'm', race: 'Man' },
  { id: 564, name: 'Lily Baggins', gender: 'f', race: 'Hobbit' },
  { id: 565, name: 'Lily Brown', gender: 'f', race: 'Hobbit' },
  { id: 566, name: 'Linda Baggins', gender: 'f', race: 'Hobbit' },
  { id: 567, name: 'Lindissë', gender: 'f', race: 'Man' },
  { id: 568, name: 'Lindórië', gender: 'f', race: 'Man' },
  { id: 569, name: 'Lobelia Sackville-Baggins', gender: 'f', race: 'Hobbit' },
  { id: 570, name: 'Longo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 571, name: 'Lóni', gender: 'm', race: 'Dwarf' },
  { id: 572, name: 'Lorgan', gender: 'm', race: 'Man' },
  { id: 573, name: 'Lórien', gender: 'm', race: 'Vala' },
  { id: 574, name: 'Lothíriel', gender: 'f', race: 'Man' },
  { id: 575, name: 'Lotho Sackville-Baggins', gender: 'm', race: 'Hobbit' },
  { id: 576, name: 'Lugdush', gender: 'm', race: 'Orc' },
  { id: 577, name: 'Lúthien', gender: 'f', race: 'Elf' },
  { id: 578, name: 'Mablung', gender: 'm', race: 'Elf' },
  { id: 579, name: 'Mablung', gender: 'm', race: 'Man' },
  { id: 580, name: 'Madoc Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 581, name: 'Maedhros', gender: 'm', race: 'Elf' },
  { id: 582, name: 'Maeglin', gender: 'm', race: 'Elf' },
  { id: 583, name: 'Farmer Maggot', gender: 'm', race: 'Hobbit' },
  { id: 584, name: 'Maglor', gender: 'm', race: 'Elf' },
  { id: 585, name: 'Mahtan', gender: 'm', race: 'Elf' },
  { id: 586, name: 'Mairen', gender: 'f', race: 'Man' },
  { id: 587, name: 'Malach', gender: 'm', race: 'Man' },
  { id: 588, name: 'Malantur', gender: 'm', race: 'Man' },
  { id: 589, name: 'Mallor', gender: 'm', race: 'Man' },
  { id: 590, name: 'Malva Headstrong', gender: 'f', race: 'Hobbit' },
  { id: 591, name: 'Malvegil', gender: 'm', race: 'Man' },
  { id: 592, name: 'Mandos', gender: 'm', race: 'Vala' },
  { id: 593, name: 'Manwë', gender: 'm', race: 'Vala' },
  { id: 594, name: 'Manwendil', gender: 'm', race: 'Man' },
  { id: 595, name: 'Marach', gender: 'm', race: 'Man' },
  { id: 596, name: 'Marcho', gender: 'm', race: 'Hobbit' },
  { id: 597, name: 'Mardil Voronwë', gender: 'm', race: 'Man' },
  { id: 598, name: 'Marhari', gender: 'm', race: 'Man' },
  { id: 599, name: 'Marhwini', gender: 'm', race: 'Man' },
  { id: 600, name: 'Marigold Gamgee', gender: 'f', race: 'Hobbit' },
  { id: 601, name: 'Marmadas Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 602, name: 'Marmadoc Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 603, name: 'Marroc Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 604, name: 'Mat Heathertoes', gender: 'm', race: 'Man' },
  { id: 605, name: 'Mauhúr', gender: 'm', race: 'Orc' },
  { id: 606, name: 'May Gamgee', gender: 'f', race: 'Hobbit' },
  { id: 607, name: 'Melian', gender: 'f', race: 'Maia' },
  { id: 608, name: 'Melilot Brandybuck', gender: 'f', race: 'Hobbit' },
  { id: 609, name: 'Melkor', gender: 'm', race: 'Vala' },
  { id: 610, name: 'Menegilda Goold', gender: 'f', race: 'Hobbit' },
  { id: 611, name: 'Meneldil', gender: 'm', race: 'Man' },
  { id: 612, name: 'Meneldor', gender: 'm', race: 'Eagle' },
  { id: 613, name: 'Tar-Meneldur', gender: 'm', race: 'Man' },
  { id: 614, name: 'Mentha Brandybuck', gender: 'f', race: 'Hobbit' },
  { id: 615, name: 'Meriadoc Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 616, name: 'Merimac Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 617, name: 'Merimas Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 618, name: 'Merry Gardner', gender: 'm', race: 'Hobbit' },
  { id: 619, name: 'Milo Burrows', gender: 'm', race: 'Hobbit' },
  { id: 620, name: 'Mîm', gender: 'm', race: 'Dwarf' },
  { id: 621, name: 'Mimosa Bunce', gender: 'f', race: 'Hobbit' },
  { id: 622, name: 'Minardil', gender: 'm', race: 'Man' },
  { id: 623, name: 'Minastan', gender: 'm', race: 'Man' },
  { id: 624, name: 'Tar-Minastir', gender: 'm', race: 'Man' },
  { id: 625, name: 'Minto Burrows', gender: 'm', race: 'Hobbit' },
  { id: 626, name: 'Mirabella Took', gender: 'f', race: 'Hobbit' },
  { id: 627, name: 'Míriel Therindë', gender: 'f', race: 'Elf' },
  { id: 628, name: 'Tar-Míriel', gender: 'f', race: 'Man' },
  { id: 629, name: 'Mithrellas', gender: 'f', race: 'Elf' },
  { id: 630, name: 'Moro Burrows', gender: 'm', race: 'Hobbit' },
  { id: 631, name: 'Morwen', gender: 'f', race: 'Man' },
  { id: 632, name: 'Morwen Steelsheen', gender: 'f', race: 'Man' },
  { id: 633, name: 'Mosco Burrows', gender: 'm', race: 'Hobbit' },
  { id: 634, name: 'Mungo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 635, name: 'Muzgash', gender: 'm', race: 'Orc' },
  { id: 636, name: 'Myrtle Burrows', gender: 'f', race: 'Hobbit' },
  { id: 637, name: 'Nahar', gender: 'm', race: 'Horse' },
  { id: 638, name: 'Náin I', gender: 'm', race: 'Dwarf' },
  { id: 639, name: 'Náin II', gender: 'm', race: 'Dwarf' },
  { id: 640, name: 'Náli', gender: 'm', race: 'Dwarf' },
  { id: 641, name: 'Nár', gender: 'm', race: 'Dwarf' },
  { id: 642, name: 'Narmacil I', gender: 'm', race: 'Man' },
  { id: 643, name: 'Narmacil II', gender: 'm', race: 'Man' },
  { id: 644, name: 'Narvi', gender: 'm', race: 'Dwarf' },
  { id: 645, name: 'Nellas', gender: 'f', race: 'Elf' },
  { id: 646, name: 'Nerdanel', gender: 'f', race: 'Elf' },
  { id: 647, name: 'Nessa', gender: 'f', race: 'Vala' },
  { id: 648, name: 'Nessanië', gender: 'f', race: 'Man' },
  { id: 649, name: 'Nienna', gender: 'f', race: 'Vala' },
  { id: 650, name: 'Niënor', gender: 'f', race: 'Man' },
  { id: 651, name: 'Nimloth', gender: 'f', race: 'Elf' },
  { id: 652, name: 'Nina Lightfoot', gender: 'f', race: 'Hobbit' },
  { id: 653, name: 'Nob', gender: 'm', race: 'Hobbit' },
  { id: 654, name: 'Nolondil', gender: 'm', race: 'Man' },
  { id: 655, name: 'Nora Bolger', gender: 'f', race: 'Hobbit' },
  { id: 656, name: 'Nori', gender: 'm', race: 'Dwarf' },
  { id: 657, name: 'Númendil', gender: 'm', race: 'Man' },
  { id: 658, name: 'Núneth', gender: 'f', race: 'Man' },
  { id: 659, name: 'Odo Proudfoot', gender: 'm', race: 'Hobbit' },
  { id: 660, name: 'Odovacar Bolger', gender: 'm', race: 'Hobbit' },
  { id: 661, name: 'Óin', gender: 'm', race: 'Dwarf' },
  { id: 662, name: 'Óin', gender: 'm', race: 'Dwarf' },
  { id: 663, name: 'Olo Proudfoot', gender: 'm', race: 'Hobbit' },
  { id: 664, name: 'Olwë', gender: 'm', race: 'Elf' },
  { id: 665, name: 'Ondoher', gender: 'm', race: 'Man' },
  { id: 666, name: 'Orchaldor', gender: 'm', race: 'Man' },
  { id: 667, name: 'Orgulas Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 668, name: 'Ori', gender: 'm', race: 'Dwarf' },
  { id: 669, name: 'Orodreth', gender: 'm', race: 'Elf' },
  { id: 670, name: 'Orodreth', gender: 'm', race: 'Man' },
  { id: 671, name: 'Oromë', gender: 'm', race: 'Vala' },
  { id: 672, name: 'Oromendil', gender: 'm', race: 'Man' },
  { id: 673, name: 'Oropher', gender: 'm', race: 'Elf' },
  { id: 674, name: 'Orophin', gender: 'm', race: 'Elf' },
  { id: 675, name: 'Ossë', gender: 'm', race: 'Maia' },
  { id: 676, name: 'Ostoher', gender: 'm', race: 'Man' },
  { id: 677, name: 'Otho Sackville-Baggins', gender: 'm', race: 'Hobbit' },
  { id: 678, name: 'Otto Boffin', gender: 'm', race: 'Hobbit' },
  { id: 679, name: 'Paladin Took I', gender: 'm', race: 'Hobbit' },
  { id: 680, name: 'Paladin Took II', gender: 'm', race: 'Hobbit' },
  { id: 681, name: 'Tar-Palantir', gender: 'm', race: 'Man' },
  { id: 682, name: 'Pallando', gender: 'm', race: 'Maia' },
  { id: 683, name: 'Pansy Baggins', gender: 'f', race: 'Hobbit' },
  { id: 684, name: 'Pearl Took', gender: 'f', race: 'Hobbit' },
  { id: 685, name: 'Pelendur', gender: 'm', race: 'Man' },
  { id: 686, name: 'Pengolodh', gender: 'm', race: 'Elf' },
  { id: 687, name: 'Peony Baggins', gender: 'f', race: 'Hobbit' },
  { id: 688, name: 'Peregrin Took', gender: 'm', race: 'Hobbit' },
  { id: 689, name: 'Pervinca Took', gender: 'f', race: 'Hobbit' },
  { id: 690, name: 'Ar-Pharazôn', gender: 'm', race: 'Man' },
  { id: 691, name: 'Pimpernel Took', gender: 'f', race: 'Hobbit' },
  { id: 692, name: 'Pippin Gardner', gender: 'm', race: 'Hobbit' },
  { id: 693, name: 'Polo Baggins', gender: 'm', race: 'Hobbit' },
  { id: 694, name: 'Ponto Baggins I', gender: 'm', race: 'Hobbit' },
  { id: 695, name: 'Ponto Baggins II', gender: 'm', race: 'Hobbit' },
  { id: 696, name: 'Poppy Chubb-Baggins', gender: 'f', race: 'Hobbit' },
  { id: 697, name: 'Porto Baggins', gender: 'm', race: 'Hobbit' },
  { id: 698, name: 'Posco Baggins', gender: 'm', race: 'Hobbit' },
  { id: 699, name: 'Primrose Boffin', gender: 'f', race: 'Hobbit' },
  { id: 700, name: 'Primrose Gardner', gender: 'f', race: 'Hobbit' },
  { id: 701, name: 'Primula Brandybuck', gender: 'f', race: 'Hobbit' },
  { id: 702, name: 'Prisca Baggins', gender: 'f', race: 'Hobbit' },
  { id: 703, name: 'Radagast', gender: 'm', race: 'Maia' },
  { id: 704, name: 'Radbug', gender: 'm', race: 'Orc' },
  { id: 705, name: 'Reginard Took', gender: 'm', race: 'Hobbit' },
  { id: 706, name: 'Rían', gender: 'f', race: 'Man' },
  { id: 707, name: 'Roäc', gender: 'm', race: 'Raven' },
  { id: 708, name: 'Robin Gardner', gender: 'm', race: 'Hobbit' },
  { id: 709, name: 'Robin Smallburrow', gender: 'm', race: 'Hobbit' },
  { id: 710, name: 'Rollo Boffin', gender: 'm', race: 'Hobbit' },
  { id: 711, name: 'Rómendacil I', gender: 'm', race: 'Man' },
  { id: 712, name: 'Rómendacil II', gender: 'm', race: 'Man' },
  { id: 713, name: 'Rorimac Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 714, name: 'Rosa Baggins', gender: 'f', race: 'Hobbit' },
  { id: 715, name: 'Rosamunda Took', gender: 'f', race: 'Hobbit' },
  { id: 716, name: 'Rose', gender: 'f', race: 'Hobbit' },
  { id: 717, name: 'Rose Gardner', gender: 'f', race: 'Hobbit' },
  { id: 718, name: 'Rosie Cotton', gender: 'f', race: 'Hobbit' },
  { id: 719, name: 'Rowan', gender: 'f', race: 'Hobbit' },
  { id: 720, name: 'Rowlie Appledore', gender: 'm', race: 'Man' },
  { id: 721, name: 'Ruby Bolger', gender: 'f', race: 'Hobbit' },
  { id: 722, name: 'Ruby Gardner', gender: 'f', race: 'Hobbit' },
  { id: 723, name: 'Rudibert Bolger', gender: 'm', race: 'Hobbit' },
  { id: 724, name: 'Rudigar Bolger', gender: 'm', race: 'Hobbit' },
  { id: 725, name: 'Rudolph Bolger', gender: 'm', race: 'Hobbit' },
  { id: 726, name: 'Rufus Burrows', gender: 'm', race: 'Hobbit' },
  { id: 727, name: 'Rúmil', gender: 'm', race: 'Elf' },
  { id: 728, name: 'Rúmil', gender: 'm', race: 'Elf' },
  { id: 729, name: 'Sadoc Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 730, name: 'Sador', gender: 'm', race: 'Man' },
  { id: 731, name: 'Saeros', gender: 'm', race: 'Man' },
  { id: 732, name: 'Ar-Sakalthôr', gender: 'm', race: 'Man' },
  { id: 733, name: 'Salmar', gender: 'm', race: 'Maia' },
  { id: 734, name: 'Salvia Brandybuck', gender: 'f', race: 'Hobbit' },
  { id: 735, name: 'Samwise Gamgee', gender: 'm', race: 'Hobbit' },
  { id: 736, name: 'Sancho Proudfoot', gender: 'm', race: 'Hobbit' },
  { id: 737, name: 'Sapphira Brockhouse', gender: 'f', race: 'Hobbit' },
  { id: 738, name: 'Saradas Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 739, name: 'Saradoc Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 740, name: 'Saruman', gender: 'm', race: 'Maia' },
  { id: 741, name: 'Sauron', gender: 'm', race: 'Maia' },
  { id: 742, name: 'Seredic Brandybuck', gender: 'm', race: 'Hobbit' },
  { id: 743, name: 'Shadowfax', gender: 'm', race: 'Horse' },
  { id: 744, name: 'Shagrat', gender: 'm', race: 'Orc' },
  { id: 745, name: 'Shelob', gender: 'f', race: 'Spider' },
  { id: 746, name: 'Sigismond Took', gender: 'm', race: 'Hobbit' },
  { id: 747, name: 'Silmariën', gender: 'f', race: 'Man' },
  { id: 748, name: 'Siriondil', gender: 'm', race: 'Man' },
  { id: 749, name: 'Smaug', gender: 'm', race: 'Dragon' },
  { id: 750, name: 'Snaga', gender: 'm', race: 'Orc' },
  { id: 751, name: 'Snaga', gender: 'm', race: 'Orc' },
  { id: 752, name: 'Soronto', gender: 'm', race: 'Man' },
  { id: 753, name: 'Strider', gender: 'm', race: 'Pony' },
  { id: 754, name: 'Stybba', gender: 'm', race: 'Pony' },
  { id: 755, name: 'Tar-Súrion', gender: 'm', race: 'Man' },
  { id: 756, name: 'Tanta Hornblower', gender: 'f', race: 'Hobbit' },
  { id: 757, name: 'Tarannon', gender: 'm', race: 'Man' },
  { id: 758, name: 'Tarcil', gender: 'm', race: 'Man' },
  { id: 759, name: 'Targon', gender: 'm', race: 'Man' },
  { id: 760, name: 'Tarondor', gender: 'm', race: 'Man' },
  { id: 761, name: 'Tarondor', gender: 'm', race: 'Man' },
  { id: 762, name: 'Tata', gender: 'm', race: 'Elf' },
  { id: 763, name: 'Ted Sandyman', gender: 'm', race: 'Man' },
  { id: 764, name: 'Telchar', gender: 'm', race: 'Dwarf' },
  { id: 765, name: 'Tar-Telemmaitë', gender: 'm', race: 'Man' },
  { id: 766, name: 'Telemnar', gender: 'm', race: 'Man' },
  { id: 767, name: 'Tar-Telperiën', gender: 'f', race: 'Man' },
  { id: 768, name: 'Telumehtar', gender: 'm', race: 'Man' },
  { id: 769, name: 'Thengel', gender: 'm', race: 'Man' },
  { id: 770, name: 'Theobald Bolger', gender: 'm', race: 'Hobbit' },
  { id: 771, name: 'Théoden', gender: 'm', race: 'Man' },
  { id: 772, name: 'Théodred', gender: 'm', race: 'Man' },
  { id: 773, name: 'Thingol', gender: 'm', race: 'Elf' },
  { id: 774, name: 'Thorin I', gender: 'm', race: 'Dwarf' },
  { id: 775, name: 'Thorin II Oakenshield', gender: 'm', race: 'Dwarf' },
  { id: 776, name: 'Thorin III Stonehelm', gender: 'm', race: 'Dwarf' },
  { id: 777, name: 'Thorondir', gender: 'm', race: 'Man' },
  { id: 778, name: 'Thorondor', gender: 'm', race: 'Eagle' },
  { id: 779, name: 'Thráin I', gender: 'm', race: 'Dwarf' },
  { id: 780, name: 'Thráin II', gender: 'm', race: 'Dwarf' },
  { id: 781, name: 'Thranduil', gender: 'm', race: 'Elf' },
  { id: 782, name: 'Thrór', gender: 'm', race: 'Dwarf' },
  { id: 783, name: 'Thuringwethil', gender: 'f', race: 'Vampire' },
  { id: 784, name: 'Tilion', gender: 'm', race: 'Maia' },
  { id: 785, name: 'Tindómiel', gender: 'f', race: 'Man' },
  { id: 786, name: 'Tobold Hornblower', gender: 'm', race: 'Hobbit' },
  { id: 787, name: 'Togo Goodbody', gender: 'm', race: 'Hobbit' },
  { id: 788, name: 'Tolman Cotton', gender: 'm', race: 'Hobbit' },
  { id: 789, name: 'Tolman Gardner', gender: 'm', race: 'Hobbit' },
  { id: 790, name: 'Tom', gender: 'm', race: 'Troll' },
  { id: 791, name: 'Tom Bombadil', gender: 'm', race: 'Unknown' },
  { id: 792, name: 'Tosto Boffin', gender: 'm', race: 'Hobbit' },
  { id: 793, name: 'Treebeard', gender: 'm', race: 'Ent' },
  { id: 794, name: 'Tulkas', gender: 'm', race: 'Vala' },
  { id: 795, name: 'Tuor', gender: 'm', race: 'Man' },
  { id: 796, name: 'Turgon', gender: 'm', race: 'Elf' },
  { id: 797, name: 'Turgon', gender: 'm', race: 'Man' },
  { id: 798, name: 'Túrin I', gender: 'm', race: 'Man' },
  { id: 799, name: 'Túrin II', gender: 'm', race: 'Man' },
  { id: 800, name: 'Túrin Turambar', gender: 'm', race: 'Man' },
  { id: 801, name: 'Uffo Boffin', gender: 'm', race: 'Hobbit' },
  { id: 802, name: 'Ufthak', gender: 'm', race: 'Orc' },
  { id: 803, name: 'Uglúk', gender: 'm', race: 'Orc' },
  { id: 804, name: 'Uinen', gender: 'f', race: 'Maia' },
  { id: 805, name: 'Ulbar', gender: 'm', race: 'Man' },
  { id: 806, name: 'Uldor', gender: 'm', race: 'Man' },
  { id: 807, name: 'Ulfang the Black', gender: 'm', race: 'Man' },
  { id: 808, name: 'Ulfast', gender: 'm', race: 'Man' },
  { id: 809, name: 'Ulmo', gender: 'm', race: 'Vala' },
  { id: 810, name: 'Ulrad', gender: 'm', race: 'Man' },
  { id: 811, name: 'Ulwarth', gender: 'm', race: 'Man' },
  { id: 812, name: 'Ungoliant', gender: 'm', race: 'Spider' },
  { id: 813, name: 'Vairë', gender: 'f', race: 'Vala' },
  { id: 814, name: 'Valacar', gender: 'm', race: 'Man' },
  { id: 815, name: 'Valandil', gender: 'm', race: 'Man' },
  { id: 816, name: 'Valandil', gender: 'm', race: 'Man' },
  { id: 817, name: 'Vána', gender: 'f', race: 'Vala' },
  { id: 818, name: 'Tar-Vanimeldë', gender: 'f', race: 'Man' },
  { id: 819, name: 'Varda', gender: 'f', race: 'Vala' },
  { id: 820, name: 'Vardamir', gender: 'm', race: 'Man' },
  { id: 821, name: 'Vardilmë', gender: 'f', race: 'Man' },
  { id: 822, name: 'Vëantur', gender: 'm', race: 'Man' },
  { id: 823, name: 'Vidugavia', gender: 'm', race: 'Man' },
  { id: 824, name: 'Vidumavi', gender: 'f', race: 'Man' },
  { id: 825, name: 'Vigo Boffin', gender: 'm', race: 'Hobbit' },
  { id: 826, name: 'Vorondil the Hunter', gender: 'm', race: 'Man' },
  { id: 827, name: 'Voronwë', gender: 'm', race: 'Elf' },
  { id: 828, name: 'Walda', gender: 'm', race: 'Man' },
  { id: 829, name: 'Wilcome Cotton', gender: 'm', race: 'Hobbit' },
  { id: 830, name: 'Wilibald Bolger', gender: 'm', race: 'Hobbit' },
  { id: 831, name: 'Wilimar Bolger', gender: 'm', race: 'Hobbit' },
  { id: 832, name: 'Will Whitfoot', gender: 'm', race: 'Hobbit' },
  { id: 833, name: 'Willie Banks', gender: 'm', race: 'Hobbit' },
  { id: 834, name: 'Wiseman Gamwich', gender: 'm', race: 'Hobbit' },
  { id: 835, name: 'Wulf', gender: 'm', race: 'Man' },
  { id: 836, name: 'Yavanna', gender: 'f', race: 'Vala' },
  { id: 837, name: 'Yávien', gender: 'f', race: 'Man' },
  { id: 838, name: 'Zamîn', gender: 'f', race: 'Man' },
  { id: 839, name: 'Zimrahin', gender: 'f', race: 'Man' },
  { id: 840, name: 'Ar-Zimrathôn', gender: 'm', race: 'Man' },
];

export function generateList(): Character[] {
  const repeats = 2;
  const resultList: Character[] = [];
  for (let i = 0; i < repeats; i++) {
    resultList.push(
      ...characters.map(c => ({ ...c, id: c.id + i * characters.length }))
    );
  }
  return resultList;
}
