import { NgForOf } from '@angular/common';
import { Component, DoCheck } from '@angular/core';
import { MatListModule } from '@angular/material/list';

@Component({
  selector: 'app-list',
  standalone: true,
  templateUrl: './list.component.html',
  imports: [MatListModule, NgForOf],
})
export class ListComponent implements DoCheck {
  private changeCycles = 0;

  ngDoCheck(): void {
    this.changeCycles++;
  }

  items: { name: string; race: string; gender: string }[] = [
    { name: 'Adalbert Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Adaldrida Bolger', gender: 'f', race: 'Hobbit' },
    { name: 'Adalgar Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Adalgrim Took', gender: 'm', race: 'Hobbit' },
    { name: 'Adamanta Chubb', gender: 'f', race: 'Hobbit' },
    { name: 'Adanel', gender: 'f', race: 'Man' },
    { name: 'Adelard Took', gender: 'm', race: 'Hobbit' },
    { name: 'Adrahil I', gender: 'm', race: 'Man' },
    { name: 'Adrahil II', gender: 'm', race: 'Man' },
    { name: 'Ar-Adûnakhôr', gender: 'm', race: 'Man' },
    { name: 'Aegnor', gender: 'm', race: 'Elf' },
    { name: 'Aerandir', gender: 'm', race: 'Unknown' },
    { name: 'Aerin', gender: 'f', race: 'Man' },
    { name: 'Aghan', gender: 'm', race: 'Man' },
    { name: 'Ailinel', gender: 'f', race: 'Man' },
    { name: 'Alatar', gender: 'm', race: 'Maia' },
    { name: 'Tar-Alcarin', gender: 'm', race: 'Man' },
    { name: 'Tar-Aldarion', gender: 'm', race: 'Man' },
    { name: 'Aldor', gender: 'm', race: 'Man' },
    { name: 'Alfrida', gender: 'f', race: 'Hobbit' },
    { name: 'Algund', gender: 'm', race: 'Man' },
    { name: 'Almarian', gender: 'f', race: 'Man' },
    { name: 'Almiel', gender: 'f', race: 'Man' },
    { name: 'Amandil', gender: 'm', race: 'Man' },
    { name: 'Tar-Amandil', gender: 'm', race: 'Man' },
    { name: 'Amaranth Brandybuck', gender: 'f', race: 'Hobbit' },
    { name: 'Amarië', gender: 'f', race: 'Elf' },
    { name: 'Amdír', gender: 'm', race: 'Elf' },
    { name: 'Amethyst Hornblower', gender: 'f', race: 'Hobbit' },
    { name: 'Amlach', gender: 'm', race: 'Man' },
    { name: 'Amlaith', gender: 'm', race: 'Man' },
    { name: 'Amras', gender: 'm', race: 'Elf' },
    { name: 'Amrod', gender: 'm', race: 'Elf' },
    { name: 'Amroth', gender: 'm', race: 'Elf' },
    { name: 'Anairë', gender: 'f', race: 'Elf' },
    { name: 'Anardil', gender: 'm', race: 'Man' },
    { name: 'Anárion', gender: 'm', race: 'Man' },
    { name: 'Tar-Anárion', gender: 'm', race: 'Man' },
    { name: 'Anborn', gender: 'm', race: 'Man' },
    { name: 'Ancalagon', gender: 'm', race: 'Dragon' },
    { name: 'Tar-Ancalimë', gender: 'f', race: 'Man' },
    { name: 'Tar-Ancalimon', gender: 'm', race: 'Man' },
    { name: 'Andreth', gender: 'f', race: 'Man' },
    { name: 'Andróg', gender: 'm', race: 'Man' },
    { name: 'Andwise Roper', gender: 'm', race: 'Hobbit' },
    { name: 'Angbor', gender: 'm', race: 'Man' },
    { name: 'Angelica Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Angelimar', gender: 'm', race: 'Man' },
    { name: 'Angelimir', gender: 'm', race: 'Man' },
    { name: 'Angrim', gender: 'm', race: 'Man' },
    { name: 'Angrod', gender: 'm', race: 'Elf' },
    { name: 'Annael', gender: 'm', race: 'Elf' },
    { name: 'Anson Roper', gender: 'm', race: 'Hobbit' },
    { name: 'Arador', gender: 'm', race: 'Man' },
    { name: 'Araglas', gender: 'm', race: 'Man' },
    { name: 'Aragorn', gender: 'm', race: 'Man' },
    { name: 'Aragorn I', gender: 'm', race: 'Man' },
    { name: 'Aragost', gender: 'm', race: 'Man' },
    { name: 'Arahad I', gender: 'm', race: 'Man' },
    { name: 'Arahad II', gender: 'm', race: 'Man' },
    { name: 'Arahael', gender: 'm', race: 'Man' },
    { name: 'Aranarth', gender: 'm', race: 'Man' },
    { name: 'Aranuir', gender: 'm', race: 'Man' },
    { name: 'Aranwë', gender: 'm', race: 'Elf' },
    { name: 'Araphant', gender: 'm', race: 'Man' },
    { name: 'Araphor', gender: 'm', race: 'Man' },
    { name: 'Arassuil', gender: 'm', race: 'Man' },
    { name: 'Aratan', gender: 'm', race: 'Man' },
    { name: 'Arathorn I', gender: 'm', race: 'Man' },
    { name: 'Arathorn II', gender: 'm', race: 'Man' },
    { name: 'Araval', gender: 'm', race: 'Man' },
    { name: 'Aravir', gender: 'm', race: 'Man' },
    { name: 'Aravorn', gender: 'm', race: 'Man' },
    { name: 'Arciryas', gender: 'm', race: 'Man' },
    { name: 'Tar-Ardamin', gender: 'm', race: 'Man' },
    { name: 'Ardamir', gender: 'm', race: 'Man' },
    { name: 'Aredhel', gender: 'f', race: 'Elf' },
    { name: 'Argeleb I', gender: 'm', race: 'Man' },
    { name: 'Argeleb II', gender: 'm', race: 'Man' },
    { name: 'Argon', gender: 'm', race: 'Elf' },
    { name: 'Argonui', gender: 'm', race: 'Man' },
    { name: 'Arien', gender: 'f', race: 'Maia' },
    { name: 'Arminas', gender: 'm', race: 'Elf' },
    { name: 'Arod', gender: 'm', race: 'Horse' },
    { name: 'Arroch', gender: '?', race: 'Horse' },
    { name: 'Artamir', gender: 'm', race: 'Man' },
    { name: 'Arthad', gender: 'm', race: 'Man' },
    { name: 'Arvedui', gender: 'm', race: 'Man' },
    { name: 'Arvegil', gender: 'm', race: 'Man' },
    { name: 'Arveleg I', gender: 'm', race: 'Man' },
    { name: 'Arveleg II', gender: 'm', race: 'Man' },
    { name: 'Arwen', gender: 'f', race: 'Half-elf' },
    { name: 'Asfaloth', gender: '?', race: 'Horse' },
    { name: 'Asgon', gender: 'm', race: 'Man' },
    { name: 'Asphodel Brandybuck', gender: 'f', race: 'Hobbit' },
    { name: 'Atanalcar', gender: 'm', race: 'Man' },
    { name: 'Tar-Atanamir', gender: 'm', race: 'Man' },
    { name: 'Atanatar I', gender: 'm', race: 'Man' },
    { name: 'Atanatar II', gender: 'm', race: 'Man' },
    { name: 'Aulë', gender: 'm', race: 'Vala' },
    { name: 'Aulendil', gender: 'm', race: 'Man' },
    { name: 'Axantur', gender: 'm', race: 'Man' },
    { name: 'Azaghâl', gender: 'm', race: 'Dwarf' },
    { name: 'Azog', gender: 'm', race: 'Orc' },
    { name: 'Bain', gender: 'm', race: 'Man' },
    { name: 'Balbo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Baldor', gender: 'm', race: 'Man' },
    { name: 'Balin', gender: 'm', race: 'Dwarf' },
    { name: 'Bandobras Took', gender: 'm', race: 'Hobbit' },
    { name: 'Barach', gender: 'm', race: 'Man' },
    { name: 'Baragund', gender: 'm', race: 'Man' },
    { name: 'Barahir', gender: 'm', race: 'Man' },
    { name: 'Barahir', gender: 'm', race: 'Man' },
    { name: 'Barahir', gender: 'm', race: 'Man' },
    { name: 'Baran', gender: 'm', race: 'Man' },
    { name: 'Baranor', gender: 'm', race: 'Man' },
    { name: 'Bard II', gender: 'm', race: 'Man' },
    { name: 'Bard the Bowman', gender: 'm', race: 'Man' },
    { name: 'Barliman Butterbur', gender: 'm', race: 'Man' },
    { name: 'Basso Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Beechbone', gender: 'm', race: 'Ent' },
    { name: 'Belba Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Beldir', gender: 'm', race: 'Man' },
    { name: 'Beldis', gender: 'f', race: 'Man' },
    { name: 'Belecthor I', gender: 'm', race: 'Man' },
    { name: 'Belecthor II', gender: 'm', race: 'Man' },
    { name: 'Beleg', gender: 'm', race: 'Man' },
    { name: 'Beleg Cúthalion', gender: 'm', race: 'Elf' },
    { name: 'Belegorn', gender: 'm', race: 'Man' },
    { name: 'Belegund', gender: 'm', race: 'Man' },
    { name: 'Belemir', gender: 'm', race: 'Man' },
    { name: 'Belen', gender: 'm', race: 'Man' },
    { name: 'Bell Goodchild', gender: 'f', race: 'Hobbit' },
    { name: 'Belladonna Took', gender: 'f', race: 'Hobbit' },
    { name: 'Bëor', gender: 'm', race: 'Man' },
    { name: 'Beorn', gender: 'm', race: 'Man' },
    { name: 'Bereg', gender: 'm', race: 'Man' },
    { name: 'Beregar', gender: 'm', race: 'Man' },
    { name: 'Beregond', gender: 'm', race: 'Man' },
    { name: 'Beregond', gender: 'm', race: 'Man' },
    { name: 'Beren', gender: 'm', race: 'Man' },
    { name: 'Beren Erchamion', gender: 'm', race: 'Man' },
    { name: 'Bereth', gender: 'f', race: 'Man' },
    { name: 'Bergil', gender: 'm', race: 'Man' },
    { name: 'Beril', gender: 'f', race: 'Man' },
    { name: 'Berilac Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Bert', gender: 'm', race: 'Troll' },
    { name: 'Berúthiel', gender: 'f', race: 'Man' },
    { name: 'Berylla Boffin', gender: 'f', race: 'Hobbit' },
    { name: 'Bifur', gender: 'm', race: 'Dwarf' },
    { name: 'Bilbo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Bilbo Gardner', gender: 'm', race: 'Hobbit' },
    { name: 'Bill', gender: 'm', race: 'Troll' },
    { name: 'Bill', gender: 'm', race: 'Pony' },
    { name: 'Bill Ferny', gender: 'm', race: 'Man' },
    { name: 'Bingo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Blanco', gender: 'm', race: 'Hobbit' },
    { name: 'Blanco Bracegirdle', gender: 'm', race: 'Hobbit' },
    { name: 'Bob', gender: 'm', race: 'Hobbit' },
    { name: 'Bodo Proudfoot', gender: 'm', race: 'Hobbit' },
    { name: 'Bofur', gender: 'm', race: 'Dwarf' },
    { name: 'Bolg', gender: 'm', race: 'Orc' },
    { name: 'Bombur', gender: 'm', race: 'Dwarf' },
    { name: 'Bór', gender: 'm', race: 'Man' },
    { name: 'Borin', gender: 'm', race: 'Dwarf' },
    { name: 'Borlach', gender: 'm', race: 'Man' },
    { name: 'Borlad', gender: 'm', race: 'Man' },
    { name: 'Boromir', gender: 'm', race: 'Man' },
    { name: 'Boromir', gender: 'm', race: 'Man' },
    { name: 'Boromir', gender: 'm', race: 'Man' },
    { name: 'Boron', gender: 'm', race: 'Man' },
    { name: 'Borondir', gender: 'm', race: 'Man' },
    { name: 'Borthand', gender: 'm', race: 'Man' },
    { name: 'Bosco Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Bowman Cotton', gender: 'm', race: 'Hobbit' },
    { name: 'Brand', gender: 'm', race: 'Man' },
    { name: 'Brandir', gender: 'm', race: 'Man' },
    { name: 'Bregalad', gender: 'm', race: 'Ent' },
    { name: 'Brego', gender: 'm', race: 'Man' },
    { name: 'Bregolas', gender: 'm', race: 'Man' },
    { name: 'Briffo Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Brodda', gender: 'm', race: 'Man' },
    { name: 'Bruno Bracegirdle', gender: 'm', race: 'Hobbit' },
    { name: 'Brytta', gender: 'm', race: 'Man' },
    { name: 'Bucca', gender: 'm', race: 'Hobbit' },
    { name: 'Buffo Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Bungo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Calimehtar', gender: 'm', race: 'Man' },
    { name: 'Caliondo', gender: 'm', race: 'Man' },
    { name: 'Calmacil', gender: 'm', race: 'Man' },
    { name: 'Tar-Calmacil', gender: 'm', race: 'Man' },
    { name: 'Camellia Sackville', gender: 'f', race: 'Hobbit' },
    { name: 'Caranthir', gender: 'm', race: 'Elf' },
    { name: 'Carc', gender: 'm', race: 'Raven' },
    { name: 'Carcharoth', gender: 'm', race: 'Werewolf' },
    { name: 'Carl Cotton', gender: 'm', race: 'Hobbit' },
    { name: 'Castamir the Usurper', gender: 'm', race: 'Man' },
    { name: 'Celandine Brandybuck', gender: 'f', race: 'Hobbit' },
    { name: 'Celeborn', gender: 'm', race: 'Elf' },
    { name: 'Celebrían', gender: 'f', race: 'Elf' },
    { name: 'Celebrimbor', gender: 'm', race: 'Elf' },
    { name: 'Celebrindor', gender: 'm', race: 'Man' },
    { name: 'Celegorm', gender: 'm', race: 'Elf' },
    { name: 'Celepharn', gender: 'm', race: 'Man' },
    { name: 'Cemendur', gender: 'm', race: 'Man' },
    { name: 'Ceorl', gender: 'm', race: 'Man' },
    { name: 'Chica Chubb', gender: 'f', race: 'Hobbit' },
    { name: 'Círdan', gender: 'm', race: 'Elf' },
    { name: 'Cirion', gender: 'm', race: 'Man' },
    { name: 'Ciryandil', gender: 'm', race: 'Man' },
    { name: 'Tar-Ciryatan', gender: 'm', race: 'Man' },
    { name: 'Ciryatur', gender: 'm', race: 'Man' },
    { name: 'Ciryon', gender: 'm', race: 'Man' },
    { name: 'Cora Goodbody', gender: 'f', race: 'Hobbit' },
    { name: 'Cotman', gender: 'm', race: 'Hobbit' },
    { name: 'Cottar', gender: 'm', race: 'Hobbit' },
    { name: 'Curufin', gender: 'm', race: 'Elf' },
    { name: 'Daeron', gender: 'm', race: 'Elf' },
    { name: 'Dagnir', gender: 'm', race: 'Man' },
    { name: 'Dáin I', gender: 'm', race: 'Dwarf' },
    { name: 'Dáin II', gender: 'm', race: 'Dwarf' },
    { name: 'Dairuin', gender: 'm', race: 'Man' },
    { name: 'Daisy Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Daisy Gardner', gender: 'f', race: 'Hobbit' },
    { name: 'Damrod', gender: 'm', race: 'Man' },
    { name: 'Déagol', gender: 'm', race: 'Hobbit' },
    { name: 'Denethor', gender: 'm', race: 'Elf' },
    { name: 'Denethor I', gender: 'm', race: 'Man' },
    { name: 'Denethor II', gender: 'm', race: 'Man' },
    { name: 'Déor', gender: 'm', race: 'Man' },
    { name: 'Déorwine', gender: 'm', race: 'Man' },
    { name: 'Derufin', gender: 'm', race: 'Man' },
    { name: 'Dervorin', gender: 'm', race: 'Man' },
    { name: 'Diamond', gender: 'f', race: 'Hobbit' },
    { name: 'Dina Diggle', gender: 'f', race: 'Hobbit' },
    { name: 'Dinodas Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Dior', gender: 'm', race: 'Half-elf' },
    { name: 'Dior', gender: 'm', race: 'Man' },
    { name: 'Dírhael', gender: 'm', race: 'Man' },
    { name: 'Dírhavel', gender: 'm', race: 'Man' },
    { name: 'Dís', gender: 'f', race: 'Dwarf' },
    { name: 'Doderic Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Dodinas Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Donnamira Took', gender: 'f', race: 'Hobbit' },
    { name: 'Dora Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Dori', gender: 'm', race: 'Dwarf' },
    { name: 'Dorlas', gender: 'm', race: 'Man' },
    { name: 'Draugluin', gender: 'm', race: 'Werewolf' },
    { name: 'Drogo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Druda Burrows', gender: 'f', race: 'Hobbit' },
    { name: 'Dudo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Duilin', gender: 'm', race: 'Man' },
    { name: 'Duinhir', gender: 'm', race: 'Man' },
    { name: 'Dúnhere', gender: 'm', race: 'Man' },
    { name: 'Durin I', gender: 'm', race: 'Dwarf' },
    { name: 'Durin II', gender: 'm', race: 'Dwarf' },
    { name: 'Durin III', gender: 'm', race: 'Dwarf' },
    { name: 'Durin IV', gender: 'm', race: 'Dwarf' },
    { name: 'Durin V', gender: 'm', race: 'Dwarf' },
    { name: 'Durin VI', gender: 'm', race: 'Dwarf' },
    { name: 'Durin VII', gender: 'm', race: 'Dwarf' },
    { name: 'Dwalin', gender: 'm', race: 'Dwarf' },
    { name: 'Eärendil', gender: 'm', race: 'Half-elf' },
    { name: 'Eärendil', gender: 'm', race: 'Man' },
    { name: 'Eärendur', gender: 'm', race: 'Man' },
    { name: 'Eärendur', gender: 'm', race: 'Man' },
    { name: 'Eärendur', gender: 'm', race: 'Man' },
    { name: 'Eärnil I', gender: 'm', race: 'Man' },
    { name: 'Eärnil II', gender: 'm', race: 'Man' },
    { name: 'Eärnur', gender: 'm', race: 'Man' },
    { name: 'Eärwen', gender: 'f', race: 'Elf' },
    { name: 'Ecthelion I', gender: 'm', race: 'Man' },
    { name: 'Ecthelion II', gender: 'm', race: 'Man' },
    { name: 'Ecthelion of the Fountain', gender: 'm', race: 'Elf' },
    { name: 'Edrahil', gender: 'm', race: 'Elf' },
    { name: 'Egalmoth', gender: 'm', race: 'Man' },
    { name: 'Egalmoth', gender: 'm', race: 'Elf' },
    { name: 'Eglantine Banks', gender: 'f', race: 'Hobbit' },
    { name: 'Eilinel', gender: 'f', race: 'Man' },
    { name: 'Elanor Gardner', gender: 'f', race: 'Hobbit' },
    { name: 'Elatan', gender: 'm', race: 'Man' },
    { name: 'Elboron', gender: 'm', race: 'Man' },
    { name: 'Eldacar', gender: 'm', race: 'Man' },
    { name: 'Eldacar', gender: 'm', race: 'Man' },
    { name: 'Eldalótë', gender: 'f', race: 'Elf' },
    { name: 'Eldarion', gender: 'm', race: 'Man' },
    { name: 'Elemmakil', gender: 'm', race: 'Elf' },
    { name: 'Elemmírë', gender: '?', race: 'Elf' },
    { name: 'Elendil', gender: 'm', race: 'Man' },
    { name: 'Tar-Elendil', gender: 'm', race: 'Man' },
    { name: 'Elendur', gender: 'm', race: 'Man' },
    { name: 'Elenwë', gender: 'f', race: 'Elf' },
    { name: 'Elfhelm', gender: 'm', race: 'Man' },
    { name: 'Elfhild', gender: 'f', race: 'Man' },
    { name: 'Elfstan Fairbairn', gender: 'm', race: 'Hobbit' },
    { name: 'Elfwine', gender: 'm', race: 'Man' },
    { name: 'Elladan', gender: 'm', race: 'Half-elf' },
    { name: 'Elmo', gender: 'm', race: 'Elf' },
    { name: 'Elrohir', gender: 'm', race: 'Half-elf' },
    { name: 'Elrond', gender: 'm', race: 'Half-elf' },
    { name: 'Elros', gender: 'm', race: 'Half-elf' },
    { name: 'Eluréd', gender: 'm', race: 'Half-elf' },
    { name: 'Elurín', gender: 'm', race: 'Half-elf' },
    { name: 'Elwing', gender: 'f', race: 'Half-elf' },
    { name: 'Emeldir', gender: 'f', race: 'Man' },
    { name: 'Enel', gender: 'm', race: 'Elf' },
    { name: 'Enerdhil', gender: 'm', race: 'Elf' },
    { name: 'Eofor', gender: 'm', race: 'Man' },
    { name: 'Eöl', gender: 'm', race: 'Elf' },
    { name: 'Éomer', gender: 'm', race: 'Man' },
    { name: 'Éomund', gender: 'm', race: 'Man' },
    { name: 'Eönwë', gender: 'm', race: 'Maia' },
    { name: 'Eorl the Young', gender: 'm', race: 'Man' },
    { name: 'Éothain', gender: 'm', race: 'Man' },
    { name: 'Éowyn', gender: 'f', race: 'Man' },
    { name: 'Eradan', gender: 'm', race: 'Man' },
    { name: 'Erchirion', gender: 'm', race: 'Man' },
    { name: 'Erellont', gender: 'm', race: 'Unknown' },
    { name: 'Erendis', gender: 'f', race: 'Man' },
    { name: 'Erestor', gender: 'm', race: 'Elf' },
    { name: 'Erkenbrand', gender: 'm', race: 'Man' },
    { name: 'Erling Greenhand', gender: 'm', race: 'Hobbit' },
    { name: 'Esmeralda Brandybuck', gender: 'f', race: 'Hobbit' },
    { name: 'Estë', gender: 'f', race: 'Vala' },
    { name: 'Estella Bolger', gender: 'f', race: 'Hobbit' },
    { name: 'Estelmo', gender: 'm', race: 'Man' },
    { name: 'Everard Took', gender: 'm', race: 'Hobbit' },
    { name: 'Falco Chubb-Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Faramir', gender: 'm', race: 'Man' },
    { name: 'Faramir Took', gender: 'm', race: 'Hobbit' },
    { name: 'Farin', gender: 'm', race: 'Dwarf' },
    { name: 'Fastolph Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Fastred', gender: 'm', race: 'Hobbit' },
    { name: 'Fastred', gender: 'm', race: 'Man' },
    { name: 'Fastred', gender: 'm', race: 'Man' },
    { name: 'Fatty Lumpkin', gender: 'm', race: 'Pony' },
    { name: 'Fëanor', gender: 'm', race: 'Elf' },
    { name: 'Felaróf', gender: 'm', race: 'Horse' },
    { name: 'Fengel', gender: 'm', race: 'Man' },
    { name: 'Ferdinand Took', gender: 'm', race: 'Hobbit' },
    { name: 'Ferumbras Took I', gender: 'm', race: 'Hobbit' },
    { name: 'Ferumbras Took II', gender: 'm', race: 'Hobbit' },
    { name: 'Ferumbras Took III', gender: 'm', race: 'Hobbit' },
    { name: 'Fíli', gender: 'm', race: 'Dwarf' },
    { name: 'Filibert Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Fimbrethil', gender: 'f', race: 'Ent' },
    { name: 'Finarfin', gender: 'm', race: 'Elf' },
    { name: 'Findegil', gender: 'm', race: 'Man' },
    { name: 'Findis', gender: 'f', race: 'Elf' },
    { name: 'Finduilas', gender: 'f', race: 'Elf' },
    { name: 'Finduilas', gender: 'f', race: 'Man' },
    { name: 'Finglas', gender: 'm', race: 'Ent' },
    { name: 'Fingolfin', gender: 'm', race: 'Elf' },
    { name: 'Fingon', gender: 'm', race: 'Elf' },
    { name: 'Finrod', gender: 'm', race: 'Elf' },
    { name: 'Finwë', gender: 'm', race: 'Elf' },
    { name: 'Firefoot', gender: 'm', race: 'Horse' },
    { name: 'Fíriel Fairbairn', gender: 'f', race: 'Hobbit' },
    { name: 'Fladrif', gender: 'm', race: 'Ent' },
    { name: 'Flambard Took', gender: 'm', race: 'Hobbit' },
    { name: 'Flói', gender: 'm', race: 'Dwarf' },
    { name: 'Folca', gender: 'm', race: 'Man' },
    { name: 'Folco Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Folcred', gender: 'm', race: 'Man' },
    { name: 'Folcwine', gender: 'm', race: 'Man' },
    { name: 'Forlong', gender: 'm', race: 'Man' },
    { name: 'Forthwini', gender: 'm', race: 'Man' },
    { name: 'Fortinbras Took I', gender: 'm', race: 'Hobbit' },
    { name: 'Fortinbras Took II', gender: 'm', race: 'Hobbit' },
    { name: 'Forweg', gender: 'm', race: 'Man' },
    { name: 'Fosco Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Fram', gender: 'm', race: 'Man' },
    { name: 'Frár', gender: 'm', race: 'Dwarf' },
    { name: 'Fréa', gender: 'm', race: 'Man' },
    { name: 'Fréaláf Hildeson', gender: 'm', race: 'Man' },
    { name: 'Fréawine', gender: 'm', race: 'Man' },
    { name: 'Freca', gender: 'm', race: 'Man' },
    { name: 'Fredegar Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Frerin', gender: 'm', race: 'Dwarf' },
    { name: 'Frodo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Frodo Gardner', gender: 'm', race: 'Hobbit' },
    { name: 'Frór', gender: 'm', race: 'Dwarf' },
    { name: 'Frumgar', gender: 'm', race: 'Man' },
    { name: 'Fuinur', gender: 'm', race: 'Man' },
    { name: 'Fundin', gender: 'm', race: 'Dwarf' },
    { name: 'Galadhon', gender: 'm', race: 'Elf' },
    { name: 'Galador', gender: 'm', race: 'Half-elf' },
    { name: 'Galadriel', gender: 'f', race: 'Elf' },
    { name: 'Galathil', gender: 'm', race: 'Elf' },
    { name: 'Galdor', gender: 'm', race: 'Elf' },
    { name: 'Galdor the Tall', gender: 'm', race: 'Man' },
    { name: 'Galion', gender: 'm', race: 'Elf' },
    { name: 'Gálmód', gender: 'm', race: 'Man' },
    { name: 'Gamil Zirak', gender: 'm', race: 'Dwarf' },
    { name: 'Gamling', gender: 'm', race: 'Man' },
    { name: 'Gandalf', gender: 'm', race: 'Maia' },
    { name: 'Gárulf', gender: 'm', race: 'Man' },
    { name: 'Gelmir', gender: 'm', race: 'Elf' },
    { name: 'Gelmir', gender: 'm', race: 'Elf' },
    { name: 'Gerda Boffin', gender: 'f', race: 'Hobbit' },
    { name: 'Gerontius Took', gender: 'm', race: 'Hobbit' },
    { name: 'Gethron', gender: 'm', race: 'Man' },
    { name: 'Ghân-buri-Ghân', gender: 'm', race: 'Man' },
    { name: 'Gildis', gender: 'f', race: 'Man' },
    { name: 'Gildor', gender: 'm', race: 'Man' },
    { name: 'Gildor Inglorion', gender: 'm', race: 'Elf' },
    { name: 'Gil-galad', gender: 'm', race: 'Elf' },
    { name: 'Gilly Brownlock', gender: 'f', race: 'Hobbit' },
    { name: 'Gilmith', gender: 'f', race: 'Half-elf' },
    { name: 'Gilraen', gender: 'f', race: 'Man' },
    { name: 'Gimilkhâd', gender: 'm', race: 'Man' },
    { name: 'Gimilzagar', gender: 'm', race: 'Man' },
    { name: 'Ar-Gimilzôr', gender: 'm', race: 'Man' },
    { name: 'Gimli', gender: 'm', race: 'Dwarf' },
    { name: 'Girion', gender: 'm', race: 'Man' },
    { name: 'Glaurung', gender: 'm', race: 'Dragon' },
    { name: 'Gléowine', gender: 'm', race: 'Man' },
    { name: 'Glirhuin', gender: 'm', race: 'Man' },
    { name: 'Glóin', gender: 'm', race: 'Dwarf' },
    { name: 'Glóin', gender: 'm', race: 'Dwarf' },
    { name: 'Glóredhel', gender: 'f', race: 'Man' },
    { name: 'Glorfindel', gender: 'm', race: 'Elf' },
    { name: 'Glorfindel', gender: 'm', race: 'Elf' },
    { name: 'Golasgil', gender: 'm', race: 'Man' },
    { name: 'Goldberry', gender: 'f', race: 'Unknown' },
    { name: 'Goldilocks Gardner', gender: 'f', race: 'Hobbit' },
    { name: 'Goldwine', gender: 'm', race: 'Man' },
    { name: 'Golfimbul', gender: 'm', race: 'Orc' },
    { name: 'Gollum', gender: 'm', race: 'Hobbit' },
    { name: 'Gorbadoc Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Gorbag', gender: 'm', race: 'Orc' },
    { name: 'Gorbulas Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Gorhendad Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Gorlim', gender: 'm', race: 'Man' },
    { name: 'Gormadoc Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Gothmog', gender: 'm', race: 'Maia' },
    { name: 'Gothmog', gender: 'm', race: 'Unknown' },
    { name: 'Gram', gender: 'm', race: 'Man' },
    { name: 'Griffo Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Gríma Wormtongue', gender: 'm', race: 'Man' },
    { name: 'Grimbeorn', gender: 'm', race: 'Man' },
    { name: 'Grimbold', gender: 'm', race: 'Man' },
    { name: 'Grishnákh', gender: 'm', race: 'Orc' },
    { name: 'Grithnir', gender: 'm', race: 'Man' },
    { name: 'Gróin', gender: 'm', race: 'Dwarf' },
    { name: 'Grór', gender: 'm', race: 'Dwarf' },
    { name: 'Gruffo Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Guilin', gender: 'm', race: 'Elf' },
    { name: 'Gundabald Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Gundahad Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Gundahar Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Gundolpho Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Gundor', gender: 'm', race: 'Man' },
    { name: 'Guthláf', gender: 'm', race: 'Man' },
    { name: 'Gwaihir', gender: 'm', race: 'Eagle' },
    { name: 'Gwindor', gender: 'm', race: 'Elf' },
    { name: 'Hador', gender: 'm', race: 'Man' },
    { name: 'Hador Lórindol', gender: 'm', race: 'Man' },
    { name: 'Halbarad', gender: 'm', race: 'Man' },
    { name: 'Haldad', gender: 'm', race: 'Man' },
    { name: 'Haldan', gender: 'm', race: 'Man' },
    { name: 'Haldar', gender: 'm', race: 'Man' },
    { name: 'Haldir', gender: 'm', race: 'Elf' },
    { name: 'Haldir', gender: 'm', race: 'Man' },
    { name: 'Haleth', gender: 'f', race: 'Man' },
    { name: 'Halfast Gamgee', gender: 'm', race: 'Hobbit' },
    { name: 'Halfred Gamgee', gender: 'm', race: 'Hobbit' },
    { name: 'Halfred Greenhand', gender: 'm', race: 'Hobbit' },
    { name: 'Hallacar', gender: 'm', race: 'Man' },
    { name: 'Hallas', gender: 'm', race: 'Man' },
    { name: 'Hallatan', gender: 'm', race: 'Man' },
    { name: 'Halmir', gender: 'm', race: 'Man' },
    { name: 'Háma', gender: 'm', race: 'Man' },
    { name: 'Hamfast of Gamwich', gender: 'm', race: 'Hobbit' },
    { name: 'Hamfast Gamgee', gender: 'm', race: 'Hobbit' },
    { name: 'Hamfast Gardner', gender: 'm', race: 'Hobbit' },
    { name: 'Hamson Gamgee', gender: 'm', race: 'Hobbit' },
    { name: 'Hanna Goldworthy', gender: 'f', race: 'Hobbit' },
    { name: 'Harding', gender: 'm', race: 'Man' },
    { name: 'Harding of the Hill', gender: 'm', race: 'Hobbit' },
    { name: 'Hareth', gender: 'm', race: 'Man' },
    { name: 'Harry Goatleaf', gender: 'm', race: 'Man' },
    { name: 'Hasufel', gender: 'm', race: 'Horse' },
    { name: 'Hatholdir', gender: 'm', race: 'Man' },
    { name: 'Helm Hammerhand', gender: 'm', race: 'Man' },
    { name: 'Hending', gender: 'm', race: 'Hobbit' },
    { name: 'Herefara', gender: 'm', race: 'Man' },
    { name: 'Heribald Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Herion', gender: 'm', race: 'Man' },
    { name: 'Herubrand', gender: 'm', race: 'Man' },
    { name: 'Herucalmo', gender: 'm', race: 'Man' },
    { name: 'Herugar Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Herumor', gender: 'm', race: 'Man' },
    { name: 'Hilda Bracegirdle', gender: 'f', race: 'Hobbit' },
    { name: 'Hildibrand Took', gender: 'm', race: 'Hobbit' },
    { name: 'Hildifons Took', gender: 'm', race: 'Hobbit' },
    { name: 'Hildigard Took', gender: 'f', race: 'Hobbit' },
    { name: 'Hildigrim Took', gender: 'm', race: 'Hobbit' },
    { name: 'Hirgon', gender: 'm', race: 'Man' },
    { name: 'Hiril', gender: 'f', race: 'Man' },
    { name: 'Hirluin', gender: 'm', race: 'Man' },
    { name: 'Hob Gammidge', gender: 'm', race: 'Hobbit' },
    { name: 'Hob Hayward', gender: 'm', race: 'Hobbit' },
    { name: 'Hobson Gamgee', gender: 'm', race: 'Hobbit' },
    { name: 'Holfast Gardner', gender: 'm', race: 'Hobbit' },
    { name: 'Holman Cotton', gender: 'm', race: 'Hobbit' },
    { name: 'Holman Greenhand', gender: 'm', race: 'Hobbit' },
    { name: 'Horn', gender: 'm', race: 'Man' },
    { name: 'Huan', gender: 'm', race: 'Wolf' },
    { name: 'Hugo Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Hugo Bracegirdle', gender: 'm', race: 'Hobbit' },
    { name: 'Hundar', gender: 'f', race: 'Man' },
    { name: 'Hunthor', gender: 'm', race: 'Man' },
    { name: 'Huor', gender: 'm', race: 'Man' },
    { name: 'Húrin', gender: 'm', race: 'Man' },
    { name: 'Húrin I', gender: 'm', race: 'Man' },
    { name: 'Húrin II', gender: 'm', race: 'Man' },
    { name: 'Hyarmendacil I', gender: 'm', race: 'Man' },
    { name: 'Hyarmendacil II', gender: 'm', race: 'Man' },
    { name: 'Îbal', gender: 'm', race: 'Man' },
    { name: 'Ibûn', gender: 'm', race: 'Dwarf' },
    { name: 'Idril', gender: 'f', race: 'Elf' },
    { name: 'Ilberic Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Ilmarë', gender: 'f', race: 'Maia' },
    { name: 'Imin', gender: 'm', race: 'Elf' },
    { name: 'Imrahil', gender: 'm', race: 'Man' },
    { name: 'Indis', gender: 'f', race: 'Elf' },
    { name: 'Ingwë', gender: 'm', race: 'Elf' },
    { name: 'Ingwion', gender: 'm', race: 'Elf' },
    { name: 'Inzilbêth', gender: 'f', race: 'Man' },
    { name: 'Ioreth', gender: 'f', race: 'Man' },
    { name: 'Iorlas', gender: 'm', race: 'Man' },
    { name: 'Írildë', gender: 'f', race: 'Man' },
    { name: 'Irimë', gender: 'f', race: 'Elf' },
    { name: 'Isembard Took', gender: 'm', race: 'Hobbit' },
    { name: 'Isembold Took', gender: 'm', race: 'Hobbit' },
    { name: 'Isengar Took', gender: 'm', race: 'Hobbit' },
    { name: 'Isengrim Took I', gender: 'm', race: 'Hobbit' },
    { name: 'Isengrim Took II', gender: 'm', race: 'Hobbit' },
    { name: 'Isengrim Took III', gender: 'm', race: 'Hobbit' },
    { name: 'Isildur', gender: 'm', race: 'Man' },
    { name: 'Isilmë', gender: 'f', race: 'Man' },
    { name: 'Isilmo', gender: 'm', race: 'Man' },
    { name: 'Isumbras Took I', gender: 'm', race: 'Hobbit' },
    { name: 'Isumbras Took II', gender: 'm', race: 'Hobbit' },
    { name: 'Isumbras Took III', gender: 'm', race: 'Hobbit' },
    { name: 'Isumbras Took IV', gender: 'm', race: 'Hobbit' },
    { name: 'Ivorwen', gender: 'f', race: 'Man' },
    { name: 'Ivy Goodenough', gender: 'f', race: 'Hobbit' },
    { name: 'Jago Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Jessamine Boffin', gender: 'f', race: 'Hobbit' },
    { name: 'Khamûl', gender: 'm', race: 'Man' },
    { name: 'Khîm', gender: 'm', race: 'Dwarf' },
    { name: 'Kíli', gender: 'm', race: 'Dwarf' },
    { name: 'Lagduf', gender: 'm', race: 'Orc' },
    { name: 'Lalia Clayhanger', gender: 'f', race: 'Hobbit' },
    { name: 'Landroval', gender: 'm', race: 'Eagle' },
    { name: 'Largo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Laura Grubb', gender: 'f', race: 'Hobbit' },
    { name: 'Lavender Grubb', gender: 'f', race: 'Hobbit' },
    { name: 'Legolas', gender: 'm', race: 'Elf' },
    { name: 'Lenwë', gender: 'm', race: 'Elf' },
    { name: 'Léod', gender: 'm', race: 'Man' },
    { name: 'Lily Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Lily Brown', gender: 'f', race: 'Hobbit' },
    { name: 'Linda Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Lindissë', gender: 'f', race: 'Man' },
    { name: 'Lindórië', gender: 'f', race: 'Man' },
    { name: 'Lobelia Sackville-Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Longo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Lóni', gender: 'm', race: 'Dwarf' },
    { name: 'Lorgan', gender: 'm', race: 'Man' },
    { name: 'Lórien', gender: 'm', race: 'Vala' },
    { name: 'Lothíriel', gender: 'f', race: 'Man' },
    { name: 'Lotho Sackville-Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Lugdush', gender: 'm', race: 'Orc' },
    { name: 'Lúthien', gender: 'f', race: 'Elf' },
    { name: 'Mablung', gender: 'm', race: 'Elf' },
    { name: 'Mablung', gender: 'm', race: 'Man' },
    { name: 'Madoc Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Maedhros', gender: 'm', race: 'Elf' },
    { name: 'Maeglin', gender: 'm', race: 'Elf' },
    { name: 'Farmer Maggot', gender: 'm', race: 'Hobbit' },
    { name: 'Maglor', gender: 'm', race: 'Elf' },
    { name: 'Mahtan', gender: 'm', race: 'Elf' },
    { name: 'Mairen', gender: 'f', race: 'Man' },
    { name: 'Malach', gender: 'm', race: 'Man' },
    { name: 'Malantur', gender: 'm', race: 'Man' },
    { name: 'Mallor', gender: 'm', race: 'Man' },
    { name: 'Malva Headstrong', gender: 'f', race: 'Hobbit' },
    { name: 'Malvegil', gender: 'm', race: 'Man' },
    { name: 'Mandos', gender: 'm', race: 'Vala' },
    { name: 'Manwë', gender: 'm', race: 'Vala' },
    { name: 'Manwendil', gender: 'm', race: 'Man' },
    { name: 'Marach', gender: 'm', race: 'Man' },
    { name: 'Marcho', gender: 'm', race: 'Hobbit' },
    { name: 'Mardil Voronwë', gender: 'm', race: 'Man' },
    { name: 'Marhari', gender: 'm', race: 'Man' },
    { name: 'Marhwini', gender: 'm', race: 'Man' },
    { name: 'Marigold Gamgee', gender: 'f', race: 'Hobbit' },
    { name: 'Marmadas Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Marmadoc Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Marroc Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Mat Heathertoes', gender: 'm', race: 'Man' },
    { name: 'Mauhúr', gender: 'm', race: 'Orc' },
    { name: 'May Gamgee', gender: 'f', race: 'Hobbit' },
    { name: 'Melian', gender: 'f', race: 'Maia' },
    { name: 'Melilot Brandybuck', gender: 'f', race: 'Hobbit' },
    { name: 'Melkor', gender: 'm', race: 'Vala' },
    { name: 'Menegilda Goold', gender: 'f', race: 'Hobbit' },
    { name: 'Meneldil', gender: 'm', race: 'Man' },
    { name: 'Meneldor', gender: 'm', race: 'Eagle' },
    { name: 'Tar-Meneldur', gender: 'm', race: 'Man' },
    { name: 'Mentha Brandybuck', gender: 'f', race: 'Hobbit' },
    { name: 'Meriadoc Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Merimac Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Merimas Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Merry Gardner', gender: 'm', race: 'Hobbit' },
    { name: 'Milo Burrows', gender: 'm', race: 'Hobbit' },
    { name: 'Mîm', gender: 'm', race: 'Dwarf' },
    { name: 'Mimosa Bunce', gender: 'f', race: 'Hobbit' },
    { name: 'Minardil', gender: 'm', race: 'Man' },
    { name: 'Minastan', gender: 'm', race: 'Man' },
    { name: 'Tar-Minastir', gender: 'm', race: 'Man' },
    { name: 'Minto Burrows', gender: 'm', race: 'Hobbit' },
    { name: 'Mirabella Took', gender: 'f', race: 'Hobbit' },
    { name: 'Míriel Therindë', gender: 'f', race: 'Elf' },
    { name: 'Tar-Míriel', gender: 'f', race: 'Man' },
    { name: 'Mithrellas', gender: 'f', race: 'Elf' },
    { name: 'Moro Burrows', gender: 'm', race: 'Hobbit' },
    { name: 'Morwen', gender: 'f', race: 'Man' },
    { name: 'Morwen Steelsheen', gender: 'f', race: 'Man' },
    { name: 'Mosco Burrows', gender: 'm', race: 'Hobbit' },
    { name: 'Mungo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Muzgash', gender: 'm', race: 'Orc' },
    { name: 'Myrtle Burrows', gender: 'f', race: 'Hobbit' },
    { name: 'Nahar', gender: 'm', race: 'Horse' },
    { name: 'Náin I', gender: 'm', race: 'Dwarf' },
    { name: 'Náin II', gender: 'm', race: 'Dwarf' },
    { name: 'Náli', gender: 'm', race: 'Dwarf' },
    { name: 'Nár', gender: 'm', race: 'Dwarf' },
    { name: 'Narmacil I', gender: 'm', race: 'Man' },
    { name: 'Narmacil II', gender: 'm', race: 'Man' },
    { name: 'Narvi', gender: 'm', race: 'Dwarf' },
    { name: 'Nellas', gender: 'f', race: 'Elf' },
    { name: 'Nerdanel', gender: 'f', race: 'Elf' },
    { name: 'Nessa', gender: 'f', race: 'Vala' },
    { name: 'Nessanië', gender: 'f', race: 'Man' },
    { name: 'Nienna', gender: 'f', race: 'Vala' },
    { name: 'Niënor', gender: 'f', race: 'Man' },
    { name: 'Nimloth', gender: 'f', race: 'Elf' },
    { name: 'Nina Lightfoot', gender: 'f', race: 'Hobbit' },
    { name: 'Nob', gender: 'm', race: 'Hobbit' },
    { name: 'Nolondil', gender: 'm', race: 'Man' },
    { name: 'Nora Bolger', gender: 'f', race: 'Hobbit' },
    { name: 'Nori', gender: 'm', race: 'Dwarf' },
    { name: 'Númendil', gender: 'm', race: 'Man' },
    { name: 'Núneth', gender: 'f', race: 'Man' },
    { name: 'Odo Proudfoot', gender: 'm', race: 'Hobbit' },
    { name: 'Odovacar Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Óin', gender: 'm', race: 'Dwarf' },
    { name: 'Óin', gender: 'm', race: 'Dwarf' },
    { name: 'Olo Proudfoot', gender: 'm', race: 'Hobbit' },
    { name: 'Olwë', gender: 'm', race: 'Elf' },
    { name: 'Ondoher', gender: 'm', race: 'Man' },
    { name: 'Orchaldor', gender: 'm', race: 'Man' },
    { name: 'Orgulas Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Ori', gender: 'm', race: 'Dwarf' },
    { name: 'Orodreth', gender: 'm', race: 'Elf' },
    { name: 'Orodreth', gender: 'm', race: 'Man' },
    { name: 'Oromë', gender: 'm', race: 'Vala' },
    { name: 'Oromendil', gender: 'm', race: 'Man' },
    { name: 'Oropher', gender: 'm', race: 'Elf' },
    { name: 'Orophin', gender: 'm', race: 'Elf' },
    { name: 'Ossë', gender: 'm', race: 'Maia' },
    { name: 'Ostoher', gender: 'm', race: 'Man' },
    { name: 'Otho Sackville-Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Otto Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Paladin Took I', gender: 'm', race: 'Hobbit' },
    { name: 'Paladin Took II', gender: 'm', race: 'Hobbit' },
    { name: 'Tar-Palantir', gender: 'm', race: 'Man' },
    { name: 'Pallando', gender: 'm', race: 'Maia' },
    { name: 'Pansy Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Pearl Took', gender: 'f', race: 'Hobbit' },
    { name: 'Pelendur', gender: 'm', race: 'Man' },
    { name: 'Pengolodh', gender: 'm', race: 'Elf' },
    { name: 'Peony Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Peregrin Took', gender: 'm', race: 'Hobbit' },
    { name: 'Pervinca Took', gender: 'f', race: 'Hobbit' },
    { name: 'Ar-Pharazôn', gender: 'm', race: 'Man' },
    { name: 'Pimpernel Took', gender: 'f', race: 'Hobbit' },
    { name: 'Pippin Gardner', gender: 'm', race: 'Hobbit' },
    { name: 'Polo Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Ponto Baggins I', gender: 'm', race: 'Hobbit' },
    { name: 'Ponto Baggins II', gender: 'm', race: 'Hobbit' },
    { name: 'Poppy Chubb-Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Porto Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Posco Baggins', gender: 'm', race: 'Hobbit' },
    { name: 'Primrose Boffin', gender: 'f', race: 'Hobbit' },
    { name: 'Primrose Gardner', gender: 'f', race: 'Hobbit' },
    { name: 'Primula Brandybuck', gender: 'f', race: 'Hobbit' },
    { name: 'Prisca Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Radagast', gender: 'm', race: 'Maia' },
    { name: 'Radbug', gender: 'm', race: 'Orc' },
    { name: 'Reginard Took', gender: 'm', race: 'Hobbit' },
    { name: 'Rían', gender: 'f', race: 'Man' },
    { name: 'Roäc', gender: 'm', race: 'Raven' },
    { name: 'Robin Gardner', gender: 'm', race: 'Hobbit' },
    { name: 'Robin Smallburrow', gender: 'm', race: 'Hobbit' },
    { name: 'Rollo Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Rómendacil I', gender: 'm', race: 'Man' },
    { name: 'Rómendacil II', gender: 'm', race: 'Man' },
    { name: 'Rorimac Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Rosa Baggins', gender: 'f', race: 'Hobbit' },
    { name: 'Rosamunda Took', gender: 'f', race: 'Hobbit' },
    { name: 'Rose', gender: 'f', race: 'Hobbit' },
    { name: 'Rose Gardner', gender: 'f', race: 'Hobbit' },
    { name: 'Rosie Cotton', gender: 'f', race: 'Hobbit' },
    { name: 'Rowan', gender: 'f', race: 'Hobbit' },
    { name: 'Rowlie Appledore', gender: 'm', race: 'Man' },
    { name: 'Ruby Bolger', gender: 'f', race: 'Hobbit' },
    { name: 'Ruby Gardner', gender: 'f', race: 'Hobbit' },
    { name: 'Rudibert Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Rudigar Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Rudolph Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Rufus Burrows', gender: 'm', race: 'Hobbit' },
    { name: 'Rúmil', gender: 'm', race: 'Elf' },
    { name: 'Rúmil', gender: 'm', race: 'Elf' },
    { name: 'Sadoc Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Sador', gender: 'm', race: 'Man' },
    { name: 'Saeros', gender: 'm', race: 'Man' },
    { name: 'Ar-Sakalthôr', gender: 'm', race: 'Man' },
    { name: 'Salmar', gender: 'm', race: 'Maia' },
    { name: 'Salvia Brandybuck', gender: 'f', race: 'Hobbit' },
    { name: 'Samwise Gamgee', gender: 'm', race: 'Hobbit' },
    { name: 'Sancho Proudfoot', gender: 'm', race: 'Hobbit' },
    { name: 'Sapphira Brockhouse', gender: 'f', race: 'Hobbit' },
    { name: 'Saradas Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Saradoc Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Saruman', gender: 'm', race: 'Maia' },
    { name: 'Sauron', gender: 'm', race: 'Maia' },
    { name: 'Seredic Brandybuck', gender: 'm', race: 'Hobbit' },
    { name: 'Shadowfax', gender: 'm', race: 'Horse' },
    { name: 'Shagrat', gender: 'm', race: 'Orc' },
    { name: 'Shelob', gender: 'f', race: 'Spider' },
    { name: 'Sigismond Took', gender: 'm', race: 'Hobbit' },
    { name: 'Silmariën', gender: 'f', race: 'Man' },
    { name: 'Siriondil', gender: 'm', race: 'Man' },
    { name: 'Smaug', gender: 'm', race: 'Dragon' },
    { name: 'Snaga', gender: 'm', race: 'Orc' },
    { name: 'Snaga', gender: 'm', race: 'Orc' },
    { name: 'Soronto', gender: 'm', race: 'Man' },
    { name: 'Strider', gender: 'm', race: 'Pony' },
    { name: 'Stybba', gender: 'm', race: 'Pony' },
    { name: 'Tar-Súrion', gender: 'm', race: 'Man' },
    { name: 'Tanta Hornblower', gender: 'f', race: 'Hobbit' },
    { name: 'Tarannon', gender: 'm', race: 'Man' },
    { name: 'Tarcil', gender: 'm', race: 'Man' },
    { name: 'Targon', gender: 'm', race: 'Man' },
    { name: 'Tarondor', gender: 'm', race: 'Man' },
    { name: 'Tarondor', gender: 'm', race: 'Man' },
    { name: 'Tata', gender: 'm', race: 'Elf' },
    { name: 'Ted Sandyman', gender: 'm', race: 'Man' },
    { name: 'Telchar', gender: 'm', race: 'Dwarf' },
    { name: 'Tar-Telemmaitë', gender: 'm', race: 'Man' },
    { name: 'Telemnar', gender: 'm', race: 'Man' },
    { name: 'Tar-Telperiën', gender: 'f', race: 'Man' },
    { name: 'Telumehtar', gender: 'm', race: 'Man' },
    { name: 'Thengel', gender: 'm', race: 'Man' },
    { name: 'Theobald Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Théoden', gender: 'm', race: 'Man' },
    { name: 'Théodred', gender: 'm', race: 'Man' },
    { name: 'Thingol', gender: 'm', race: 'Elf' },
    { name: 'Thorin I', gender: 'm', race: 'Dwarf' },
    { name: 'Thorin II Oakenshield', gender: 'm', race: 'Dwarf' },
    { name: 'Thorin III Stonehelm', gender: 'm', race: 'Dwarf' },
    { name: 'Thorondir', gender: 'm', race: 'Man' },
    { name: 'Thorondor', gender: 'm', race: 'Eagle' },
    { name: 'Thráin I', gender: 'm', race: 'Dwarf' },
    { name: 'Thráin II', gender: 'm', race: 'Dwarf' },
    { name: 'Thranduil', gender: 'm', race: 'Elf' },
    { name: 'Thrór', gender: 'm', race: 'Dwarf' },
    { name: 'Thuringwethil', gender: 'f', race: 'Vampire' },
    { name: 'Tilion', gender: 'm', race: 'Maia' },
    { name: 'Tindómiel', gender: 'f', race: 'Man' },
    { name: 'Tobold Hornblower', gender: 'm', race: 'Hobbit' },
    { name: 'Togo Goodbody', gender: 'm', race: 'Hobbit' },
    { name: 'Tolman Cotton', gender: 'm', race: 'Hobbit' },
    { name: 'Tolman Gardner', gender: 'm', race: 'Hobbit' },
    { name: 'Tom', gender: 'm', race: 'Troll' },
    { name: 'Tom Bombadil', gender: 'm', race: 'Unknown' },
    { name: 'Tosto Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Treebeard', gender: 'm', race: 'Ent' },
    { name: 'Tulkas', gender: 'm', race: 'Vala' },
    { name: 'Tuor', gender: 'm', race: 'Man' },
    { name: 'Turgon', gender: 'm', race: 'Elf' },
    { name: 'Turgon', gender: 'm', race: 'Man' },
    { name: 'Túrin I', gender: 'm', race: 'Man' },
    { name: 'Túrin II', gender: 'm', race: 'Man' },
    { name: 'Túrin Turambar', gender: 'm', race: 'Man' },
    { name: 'Uffo Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Ufthak', gender: 'm', race: 'Orc' },
    { name: 'Uglúk', gender: 'm', race: 'Orc' },
    { name: 'Uinen', gender: 'f', race: 'Maia' },
    { name: 'Ulbar', gender: 'm', race: 'Man' },
    { name: 'Uldor', gender: 'm', race: 'Man' },
    { name: 'Ulfang the Black', gender: 'm', race: 'Man' },
    { name: 'Ulfast', gender: 'm', race: 'Man' },
    { name: 'Ulmo', gender: 'm', race: 'Vala' },
    { name: 'Ulrad', gender: 'm', race: 'Man' },
    { name: 'Ulwarth', gender: 'm', race: 'Man' },
    { name: 'Ungoliant', gender: 'm', race: 'Spider' },
    { name: 'Vairë', gender: 'f', race: 'Vala' },
    { name: 'Valacar', gender: 'm', race: 'Man' },
    { name: 'Valandil', gender: 'm', race: 'Man' },
    { name: 'Valandil', gender: 'm', race: 'Man' },
    { name: 'Vána', gender: 'f', race: 'Vala' },
    { name: 'Tar-Vanimeldë', gender: 'f', race: 'Man' },
    { name: 'Varda', gender: 'f', race: 'Vala' },
    { name: 'Vardamir', gender: 'm', race: 'Man' },
    { name: 'Vardilmë', gender: 'f', race: 'Man' },
    { name: 'Vëantur', gender: 'm', race: 'Man' },
    { name: 'Vidugavia', gender: 'm', race: 'Man' },
    { name: 'Vidumavi', gender: 'f', race: 'Man' },
    { name: 'Vigo Boffin', gender: 'm', race: 'Hobbit' },
    { name: 'Vorondil the Hunter', gender: 'm', race: 'Man' },
    { name: 'Voronwë', gender: 'm', race: 'Elf' },
    { name: 'Walda', gender: 'm', race: 'Man' },
    { name: 'Wilcome Cotton', gender: 'm', race: 'Hobbit' },
    { name: 'Wilibald Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Wilimar Bolger', gender: 'm', race: 'Hobbit' },
    { name: 'Will Whitfoot', gender: 'm', race: 'Hobbit' },
    { name: 'Willie Banks', gender: 'm', race: 'Hobbit' },
    { name: 'Wiseman Gamwich', gender: 'm', race: 'Hobbit' },
    { name: 'Wulf', gender: 'm', race: 'Man' },
    { name: 'Yavanna', gender: 'f', race: 'Vala' },
    { name: 'Yávien', gender: 'f', race: 'Man' },
    { name: 'Zamîn', gender: 'f', race: 'Man' },
    { name: 'Zimrahin', gender: 'f', race: 'Man' },
    { name: 'Ar-Zimrathôn', gender: 'm', race: 'Man' },
  ];
}
